### ISSUE TITLE
当存在空白的时候，点击报错

### ISSUE THREAD

**Issue by 1144075799** [ruilisi/fortune-sheet#10]
你好，我已经在公司内部测试使用了页面，让我们点击空白的区域的时候会发生如下报错:
![77681650941777_ pic](https://user-images.githubusercontent.com/38463468/165211221-7fb3e3fe-c02c-407a-a404-35576c7148b3.jpg)
![77691650941822_ pic](https://user-images.githubusercontent.com/38463468/165211266-a9ddf478-8179-4b2f-b1f4-9e5ed70c277c.jpg)

**Comment by zyc9012** [comment]
Fixed.
