### ISSUE TITLE
请问如何二次使用data参数重新初始化?

### ISSUE THREAD

**Issue by Minfee** [ruilisi/fortune-sheet#100]
**Is your feature request related to a problem? Please describe.**
目前表格的初始化为获取到远端data配置后完成第一次加载，但如果使用useState存储data的时候，当data更新后表格不会重新渲染到新的data配置，不知道是否有其他方法可以手动/自动触发这个加载？

**Describe the solution you'd like**
当data存储在useSatate时，若更新data则表格重新渲染到新的data

**Comment by shuanhukexuejia** [comment]
目前还没有办法二次初始化，可在后续加入refreshData供外部调用。你这边是需要在workbook外更新data配置？

**Comment by Minfee** [comment]
是的，我的流程是设计者在空白表格直接设计页面，然后通过getSheet的接口取到data，然后使用的时候将之前拿到的data直接装载进去，但是切换表格的时候发现没有更新的接口。
请问可以提供修改代码的位置吗，一方面我确实比较着急，另一方面也想参与共建哈哈

**Comment by shuanhukexuejia** [comment]
packages/react/src/components/Workbook/index.tsx 219行开始是初始化过程，packages/react/src/components/Workbook/api.ts里添加暴露出来的api

**Comment by Minfee** [comment]
多谢 我研究下

**Comment by Minfee** [comment]
另外想问下0.8版本到0.9版本是不是生成的data有区别？   用0.8的data在0.9无法load出来数据 只有边框可以显示

**Comment by shuanhukexuejia** [comment]
你的数据是放的data还是cellData， 新版本用的cellData进行的初始化，
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/84694078/202383515-343d08d6-65ed-4f5f-b304-e6a6735e7e76.png">

**Comment by Minfee** [comment]
用的是data.data  那应该换成data.cellData就可以了哈

**Comment by shuanhukexuejia** [comment]
> 用的是data.data 那应该换成data.cellData就可以了哈

是这样的

**Comment by Minfee** [comment]
好的 多谢

**Comment by Minfee** [comment]
似乎还是有些问题 是现在getSheet函数拿到的值不能直接赋给data参数了吗 我看现在拿到的也是data 不是celldata

**Comment by shuanhukexuejia** [comment]
这边是有些不统一了，要暂时解决的话，需要一个将data转换为celldata的函数

**Comment by Minfee** [comment]
好的 我先降到低版本   目前涉及到的页面比较多

**Comment by shuanhukexuejia** [comment]
可以，这边将对这部分进行一些优化
