### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by nicoesiea** [ruilisi/fortune-sheet#105]
**Describe the bug**
On my application I was forced to add this custom CSS:
````
:host{
  ::ng-deep {
    .fortune-fx-input,
    .fortune-name-box-container,
    .fortune-toolbar-item,
    .luckysheet-cell-input {
      color:black
    }
    .fortune-fx-editor {
      background-color: white;
    }
    .fortune-left-top {
      background-color: rgba(194, 194, 194, 0.4);
    }
    .fortune-fx-input{
      text-align: left;
    }
  }
}
````
Even after adding the dist CSS:
````"node_modules/@fortune-sheet/react/dist/index.css"````

**Expected behavior**
Did I make something wrong? 
If not, it is possible to add this style directly on the default stylesheet?

**Screenshots**
![image](https://user-images.githubusercontent.com/4542315/204549709-36879d0d-b9c7-4a38-99fc-154c9f27e0ce.png)
![image](https://user-images.githubusercontent.com/4542315/204550045-35083952-276f-4f28-aadf-15b010985fa4.png)

**Comment by shuanhukexuejia** [comment]
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/84694078/204734522-14c5e240-45b5-46ae-9189-9cd4f52afee5.png">
i just added the style in chrome dev tools, and it works. Try more styles?

**Comment by shuanhukexuejia** [comment]
Seems no other file can be imported. Have you tried more styles? or what is the specific problem

**Comment by nicoesiea** [comment]
It can be due to my own CSS style... but may I suggest overriding the potential own style by adding the one I suggest in my first comment?
At least, it will be possible to re-override it, but by default, it could be better to have it visible, isn't it?

**Comment by Qaplagzy** [comment]
hi, we discussed your issue internally then. Can you provide a minimal reproducible demo so that we can debug and solve it locally?

**Comment by nicoesiea** [comment]
As I said, it can be due to my own stylesheet. I override the style like this:
```
:host{
  ::ng-deep {
    .fortune-fx-input,
    .fortune-name-box-container,
    .fortune-toolbar-item,
    .luckysheet-cell-input {
      color:black
    }
    .fortune-fx-editor {
      background-color: white;
    }
    .fortune-left-top {
      background-color: rgba(194, 194, 194, 0.4);
    }
    .fortune-fx-input{
      text-align: left;
    }
    .luckysheet-bottom-controll-row {
      display: none;
    }
    .luckysheet-scrollbars.luckysheet-scrollbar-ltr.luckysheet-scrollbar-x {
      width: 95% !important;
    }
  }
}
```

And here it is working fine. 
My suggestion is to force the default style inside the plugin, to avoid this kind of behavior, but this is just nice to have ;)
I do believe this is not urgent - and maybe not necessary - there are others topic more important ;)

**Comment by gudipudipradeep** [comment]
@nicoesiea can we make specific column as readinly by using css..? If so how to identify id or class of the specific column

**Comment by nicoesiea** [comment]
I'm sorry @gudipudipradeep but I do not how to help you to do this

**Comment by nicoesiea** [comment]
Hello,
Testing the new 0.11.0 version, I started by removing my own CSS (added inside my component)
Here is the result:
![image](https://user-images.githubusercontent.com/4542315/209642817-0659b1d4-4db8-4875-8f90-350e4274cee9.png)

As we can see:
- the function block is still black
- the text to display the selected cell is white (with a white background)
- the white-on-white color for the value/formula field
- and the add row button is no more visible, but the space is still present

Is there at least a possibility to remove the space after the data table/array if there is no add row button?
For the rest, is seems to be my own CSS the issue, do not worry on this ;)
