### ISSUE TITLE
Spanish format dropdown list missing element

### ISSUE THREAD

**Issue by nicoesiea** [ruilisi/fortune-sheet#107]
**Describe the bug**
There are two empty items in the format dropdown

**To Reproduce**
![image](https://user-images.githubusercontent.com/4542315/204563361-5f47d38f-2437-46d2-b49d-7ffe89a2758e.png)

In the DOM I can see:
![image](https://user-images.githubusercontent.com/4542315/204563261-6e3470af-9e68-4957-8790-b90f0b1fc425.png)

**Expected behavior**
We should have values or nothing, but no empty line

**Additional context**
It happens only with ES language.
If I switch in English it is working fine:
![image](https://user-images.githubusercontent.com/4542315/204563744-c3e49566-11a5-42c3-a9e0-43610faba9ab.png)

**Comment by shuanhukexuejia** [comment]
<img width="486" alt="image" src="https://user-images.githubusercontent.com/84694078/204721051-761fcd63-9e53-42c6-8a67-fe3d14840cf6.png">
'partir' should be 'split' then it will display as a split line, will fix it soon.
In addition, the translation is incomplete, still need some extra work.

**Comment by Qaplagzy** [comment]
Contributing Spanish translations to this project is also appreciated if you need to use the Spanish version.

**Comment by nicoesiea** [comment]
Sorry but I'm not Spanish speaker - and my only knowledge is on google translate tool :)
