### ISSUE TITLE
Scrollbar out of the box

### ISSUE THREAD

**Issue by nicoesiea** [ruilisi/fortune-sheet#108]
**Describe the bug**
The horizontal scrollbar is out of the container. 
The scroll bar width exceeds the width of the container

**To Reproduce**
Default behavior

**Expected behavior**
The scrollbar width stays inside the container

**Screenshots**
![image](https://user-images.githubusercontent.com/4542315/204762239-538f5c90-0c62-408e-a651-585f8dc189e6.png)
I can change my application setting to use a discreet scrollbar design, even in this mode we can see the width is too big:
![image](https://user-images.githubusercontent.com/4542315/204762556-d611a1a7-0dda-47ed-98e7-675d5716caec.png)

**Additional context**
I'm using Angular 13 with the react plugin loaded with a wrapper (just for you to know)

**Comment by nicoesiea** [comment]
It seems there is an issue with the calculation of these two values
![image](https://user-images.githubusercontent.com/4542315/204765415-31434645-dd9b-48f9-8ac6-6c5f61639fa9.png)

**Comment by Qaplagzy** [comment]
ok, we'll look into that.

**Comment by gudipudipradeep** [comment]
added fallowing css it fitting for all devices configuration. but sheet become readonly. not sure why like this

div.luckysheet-scrollbars{
  width: 96% !important;
}

**Comment by nicoesiea** [comment]
To me, it solves my issue - because I'm using read-only mode... But agree it is just a workaround
Let's way and see - thank you very much @gudipudipradeep ;)

**Comment by nicoesiea** [comment]
It looks like this bug was not fixed in the latest version 0.10.0
![image](https://user-images.githubusercontent.com/4542315/207288706-f3708193-db1f-4ddc-8f6c-a0021a7e0935.png)

Was it supposed to be? I'm now using:
-     "@fortune-sheet/core": "^0.10.0",
-     "@fortune-sheet/react": "^0.10.0",
