### ISSUE TITLE
Canva dimension auto resize

### ISSUE THREAD

**Issue by nicoesiea** [ruilisi/fortune-sheet#109]
**Is your feature request related to a problem? Please describe.**
When I resize the container where the sheet is displayed, the canvas dimension does not update and the rendering does not match the new size.
![image](https://user-images.githubusercontent.com/4542315/204775027-e19bfdc9-786d-45ac-8216-605015aa2498.png)

**Describe the solution you'd like**
Having a resize observer to adapt the canvas width and height every time the values are updated

**Describe alternatives you've considered**
I will try to develop this observer on my own side (in my own application) to fix the size by myself - but it could be better to have this fix included in the lib

**Additional context**
I'm using Angular 13 with the react plugin loaded with a wrapper (just for you to know)

**Comment by shuanhukexuejia** [comment]
<img width="635" alt="image" src="https://user-images.githubusercontent.com/84694078/205015921-2f6c8f7e-2e75-48af-b701-c74f28aadc31.png">
The canvas upate only on window resize not container, we have encountered a similar situation, we temporarily resolved it by forced update on the workbook. Time permitting, we will investigate this problem again

**Comment by nicoesiea** [comment]
Ok, thank
May I ask which function I can call to force the refresh?

**Comment by shuanhukexuejia** [comment]
```
```

**Comment by nicoesiea** [comment]
Humm when I trigger the event manually in the console, it is working fine,
But if I add the dispatchEvent in my Angular application, nothing is happening :(

**Comment by nicoesiea** [comment]
I have to find a good place to throw the event... My job to do this :(
Thank you btw

**Comment by nicoesiea** [comment]
With Angular I was obliged to add a timeout in my controller to have the correct behavior
I would really prefer to have this feature auto managed by the component himself ;)

**Comment by gudipudipradeep** [comment]
@czsandszs can we make specific column as readinly by using css..? If so how to identify id or class of the specific column

**Comment by kimgysen** [comment]
Related, I've bumped into the same problem. 

The resize event appears to work, but internally something doesn't get calculated quite right: 

![image](https://user-images.githubusercontent.com/4547364/209451585-abae7fc6-f541-4363-92a5-9d1381e9d2f5.png)

On resizing smaller and then back to the original size, the following occurs: 

![image](https://user-images.githubusercontent.com/4547364/209451575-1b614e53-77d8-418a-a26e-e42fcd56ee87.png)

It would appear as if the width of the container fortune-cell-area is not correctly re-calculated.

**Comment by shuanhukexuejia** [comment]
@kimgysen Try setting ms to 100, just make sure the change of container has been displayed when dispatching 'resize' event

**Comment by kimgysen** [comment]
@shuanhukexuejia It's interesting. 

Your suggestion: 

![image](https://user-images.githubusercontent.com/4547364/209800754-a822bb88-2adf-4991-9ac3-2c473cff8f4c.png)

Doesn't appear to work: 

![image](https://user-images.githubusercontent.com/4547364/209801014-951f5487-7a87-45cf-8f5f-3404faad30f5.png)

On the opposite, triggering the event twice does work, which is strange: 

![image](https://user-images.githubusercontent.com/4547364/209801761-1e1eba07-9192-4ca1-affc-a5870d3e2c20.png)

I assume that on resize of the window this event will trigger many times so that it may not be noticeable. 
But maybe there is something small that causes this (?).

**Comment by kimgysen** [comment]
I've been playing around with it. Strangely the vertical scaling doesn't appear to have this problem. 
I have no explanation for this... 
For me it's not blocking anyways, the double event although weird creates the correct behavior.
