### ISSUE TITLE
Assignment regarding Excel export

### ISSUE THREAD

**Issue by maifeeulasad** [ruilisi/fortune-sheet#11]
**Is your feature request related to a problem? Please describe.**
Export excel

**Describe the solution you'd like**
To have a download button, which will directly download as Excel

**Describe alternatives you've considered**
use something like `exceljs`

**Additional context**
_Included in roadmap_

_**If no one else is working on it, can I get assigned to it?**_

**Comment by zyc9012** [comment]
@maifeeulasad Yes, you can work on this, thank you!

Be sure to make it a new package, as `exceljs` is a huge depencency (1.2MB ungzipped), it should be optionally included by developers.

**Comment by maifeeulasad** [comment]
@zyc9012 Thanks a lot. I'll share all the relevant and related links on this thread.

**Comment by kilik52** [comment]
> @zyc9012 Thanks a lot. I'll share all the relevant and related links on this thread.

hi, any progress on this?

**Comment by maifeeulasad** [comment]
@kilik52, here is the repo on which I'm working: https://github.com/maifeeulasad/to-spreadsheet.

We should be able to see some updates within a week or two.

**Comment by sankethpb** [comment]
@maifeeulasad  @zyc9012 
Could you please let us know approximately when this will be available?

**Comment by maifeeulasad** [comment]
Dear,

I will try to get some work done on `to-spreadsheet`. If you don't hear from me within a week, be pretty sure that I've lost interest in this or I'm simply down at this moment.

Have a good weekend. 🥂

**Comment by maifeeulasad** [comment]
I wanted to let you know that there has been some progress on the `to-spreadsheet` front. It seems we might be seeing some light at the end of the tunnel.

Please review the code here: https://github.com/maifeeulasad/to-spreadsheet/tree/v1.0.0

NB: lots of features to be implemented. Right now it just generates XLSX, that's all.

**Comment by zyc9012** [comment]
Thank you @maifeeulasad.

**Comment by sanchit3008** [comment]
https://github.com/Corbe30/FortuneExcel
