### ISSUE TITLE
When readOnly mode, text field formula bar is still editable + the user can swtich the sheet position

### ISSUE THREAD

**Issue by nicoesiea** [ruilisi/fortune-sheet#111]
**Describe the bug**
When the config **allowEdit** is false, the text field in the formula bar should not be editable 
*AND*
The user can still move the sheet name from the right or left position

**To Reproduce**
1. Set config allowEdit to false
2. Select a cell
3. click on the formula bar and edit the content (the cell value is not updated, but the formula bar value should be editable)
4. Open an Excel file with more than 1 sheet (2 or 3)
5. You can still move (drag and drop) one sheet before or after another

**Expected behavior**
The text field should not be editable (read-only) and the sheet order should not be changed

**Screenshots**
![image](https://user-images.githubusercontent.com/4542315/204782855-61bbe61f-eba6-44b4-9344-4d1a2dc4d0a8.png)
![image](https://user-images.githubusercontent.com/4542315/204856976-4f58b2c0-65cc-4df7-a06b-3cdc2ba334f7.png)

**Comment by nicoesiea** [comment]
I was believing it could be possible to bloc the input with CSS on my side (with pointer-events: none)
But this is not input text field, this is already managed by script :(

**Comment by shuanhukexuejia** [comment]
Got it, will fix it soon. Thanks for your report

**Comment by Qaplagzy** [comment]
#139

**Comment by nicoesiea** [comment]
Hello,
Testing the new 0.11.0 version, I can see the sheet position switch is blocked on read-only mode, thank you.
However, the edition is still possible - even if the value is not reported into the cell, the user is still able to edit the field:
![image](https://user-images.githubusercontent.com/4542315/209643667-9d9362bc-236e-435f-aa05-705f9db44d6e.png)

**Comment by lvjing-tuzhi** [comment]
This issue has been fixed and will be released in the next release。
