### ISSUE TITLE
When Formula edition, sheet changing breaks the entire component

### ISSUE THREAD

**Issue by nicoesiea** [ruilisi/fortune-sheet#112]
**Describe the bug**
If the **allowEdit** is **true**
If the user starts editing a formula, if he changes the sheet (if the user clicks on sheet 2 per example) it will break the entire component.

**To Reproduce**
1. render the Workbook with **allowEdit={true}**
2. start to edit a cell with the formula (like =B1+B2)
3. validate the edition and add a new Sheet
4. back to the first sheet
5. edit the formula cell
6. click on sheet 2 

**Expected behavior**
The formula edition should be canceled and the new sheet should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/4542315/204852619-961bb29f-1d11-426c-b2ed-5005616e5c2d.png)
![image](https://user-images.githubusercontent.com/4542315/204852716-1968fa21-ff32-40d0-b11f-1dac2577b90f.png)
![image](https://user-images.githubusercontent.com/4542315/204853485-92c8c371-5292-4a1b-92a0-a280e7cb42aa.png)

**Additional context**
I'm using Angular 13 with the react plugin loaded with a wrapper (just for you to know)

**Comment by shuanhukexuejia** [comment]
I didn't reproduce the bug but it does need optimization, have added to todo-list

**Comment by gazedreamily** [comment]
We hope our work on this issues can work correctly, just try our new versionWe hope our work on this issues can work correctly, just try our new version @nicoesiea 
#130

**Comment by nicoesiea** [comment]
Hello,
Testing the new 0.11.0 version, I can see this bug is fixed. Thank you very much
