### ISSUE TITLE
Sheet right and left arrows

### ISSUE THREAD

**Issue by nicoesiea** [ruilisi/fortune-sheet#113]
**Describe the bug**
Nothing happens when I click on these two bottom sheet name arraws
![image](https://user-images.githubusercontent.com/4542315/204859881-3d3153f9-bf8a-483b-8816-60eff7730777.png)

**To Reproduce**
1. Open an Excel file with multiple sheets
2. click on the double left arrows

**Expected behavior**
Maybe they are supposed to move the view from one sheet to the next (or the previous)

**Screenshots**
![image](https://user-images.githubusercontent.com/4542315/204860176-b3032ef9-e064-4ef6-ace5-193a0b500266.png)

**Additional context**
I'm using Angular 13 with the react plugin loaded with a wrapper (just for you to know)

**Comment by shuanhukexuejia** [comment]
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/84694078/204987538-ffcdc3fe-3e07-49a1-ae5b-cf5bb731c9d2.png">
They are just for scrolling the sheet list. We will consider some optimizations to it

**Comment by nicoesiea** [comment]
Hello,
Testing the new 0.11.0 version, these right and left arrows are still not working :(

**Comment by lvjing-tuzhi** [comment]
These two buttons are used to slide the sheet bar and have been optimized.
