### ISSUE TITLE
Circular reference

### ISSUE THREAD

**Issue by ChrisdeG** [ruilisi/fortune-sheet#115]
**Describe the bug**
Error: Circular dependency: node_modules/@formulajs/formulajs/lib/math-trig.js -> node_modules/@formulajs/formulajs/lib/statistical.js -> node_modules/@formulajs/formulajs/lib/math-trig.js

**Comment by shuanhukexuejia** [comment]
Ok, we will look into it

**Comment by Qaplagzy** [comment]
it's about @formulajs/formulajs
