### ISSUE TITLE
支持预览吗

### ISSUE THREAD

**Issue by hadoop835** [ruilisi/fortune-sheet#116]
支持预览吗

**Comment by shuanhukexuejia** [comment]
你是指线上demo [fortune-sheet-demo](https://ruilisi.github.io/fortune-sheet-demo/) ？

**Comment by hadoop835** [comment]
@shuanhukexuejia 不是demo，就是预览内容，不可用编辑内容

**Comment by shuanhukexuejia** [comment]
设置allowEditt={false}，不过目前还有些问题需要修复 #112
