### ISSUE TITLE
onChange cell getting issue.

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#117]
const onChange = useCallback((d: Sheet[]) => {
	d[0]["data"][1][1]={"ct": {"fa": "General","t": "g"},"m": "Nameofthescript","v": "Name of the script","bg": "#858a7e","ht": "0",};
    console.info(d[0]["data"]);
  }, []);

  return <Workbook data={settings}  onChange={onChange}/>;

Please can suggest the example for onChange event for each cell. I couldn't find on it. 
above one is failing while I set the cell value.

**Comment by gudipudipradeep** [comment]
Please can you share the article on rows and column updates example.

**Comment by shuanhukexuejia** [comment]
https://ruilisi.github.io/fortune-sheet-docs/guide/api.html#overview, API is avaible via the ref of Workbook

**Comment by gudipudipradeep** [comment]
import React, { useRef, useState, useEffect, useCallback } from "react";
import ReactDOM from 'react-dom';
import "./styles.css";
import { Workbook } from "@fortune-sheet/react";
import "@fortune-sheet/react/dist/index.css"
import { produce } from "immer";
import { ComponentMeta, ComponentStory } from "@storybook/react";
import { Sheet } from "@fortune-sheet/core";

export default {
  component: Workbook,
} as ComponentMeta<typeof Workbook>;

const settings =  [
{
    name: "Terminal",
    id: 0,
    status: 1,
	defaultRowHeight: 20,
	scrollLeft: 0,
	column: 25,
	row: 20,
	config: {rowlen: {"0": 50}},
    celldata: [ {"r": 0,"c": 0,"v": {ct: {fa: "General", t: "g"},m:"Nameofthescript",v:"Name of the script","bg": "#858a7e","ht":"0"},},
			{"r": 0,"c": 1,"v": {ct: {fa: "General", t: "g"},m:"BuyRate",v:"Buy Rate","bg": "#00ff00","ht":"0"},},
			{"r": 0,"c": 2,"v": {ct: {fa: "General", t: "g"},m:"Quantity",v:"Quantity","bg": "#00ff00","ht":"0"},}
		]
  }
 ];

const App = () => {
 const [sheets, setSheets] = useState(settings);
  const onChange = useCallback((d: Sheet[]) => {
	setSheets(d);
  }, []);
  return <Workbook data={settings}  onChange={onChange}/>;
};
export default App;
-----------------------------------------------------------------------------------------------------------------------------
above code failing with semi colon issue
export default {
  component: Workbook,
} as ComponentMeta<typeof Workbook>;


Please can you guide what went wrong with

**Comment by shuanhukexuejia** [comment]
Maybe you should delete ',' at 
<img width="239" alt="image" src="https://user-images.githubusercontent.com/84694078/205876239-d4b7e9f8-752f-43f5-8353-16ece51e7e9f.png">.
In addition, this error is not related to this project.

**Comment by gudipudipradeep** [comment]
Thanks, please can you provide js example. We have only typescript examples. It will be helpful
