### ISSUE TITLE
Multiple Instance Issue Solution

### ISSUE THREAD

**Issue by yusufkayaer** [ruilisi/fortune-sheet#118]
Hello,

I have a question that  how did you solve the multiple instance problem.  😄 
I'm trying to solve this problem in my local luckySheet project.

Regards.

**Comment by zyc9012** [comment]
Hi @yusufkayaer,

The idea was simple - to avoid defining global variables (e.g. `window.luckysheet*`, global vars on modules, ...). We took advantage of [React context](https://reactjs.org/docs/context.html) and put global vars there. Still require a deep rewrite of the code though.
