### ISSUE TITLE
Workbook sheets does not re-render when I update the data prop.

### ISSUE THREAD

**Issue by yusufkayaer** [ruilisi/fortune-sheet#119]
**Describe the bug**
Workbook sheets does not re-render when I change the data prop within a button click event.

**To Reproduce**
1. Go to [fortune-sheet-react-sample](https://github.com/yusufkayaer/fortune-sheet-react-sample) repo and clone it.
2. yarn install
3. yarn start
4. When I click the "Set New Sheets" button then I create the new state with newData object and pass it to Workbook's data prop. But Workbook components does not re-render with new sheet and cells.

**Expected behavior**
I expect the Workbook component to re-render with new sheet.

**Comment by Qaplagzy** [comment]
Hello, someone encountered a similar problem in issue #100. We have put the solution to this problem on the agenda and will solve it within a week.🍺

**Comment by kimgysen** [comment]
@Qaplagzy It appears that the same appears to happen for row / column. On updating the settings, the number of columns / rows remains the same.  
Granted, the docs mention: 
"Usage: The default number of columns in an empty workbook
" 
But I would expect the number of columns / rows to change when updating the props...

**Comment by lvjing-tuzhi** [comment]
@kimgysen The problem has been solved

**Comment by kimgysen** [comment]
Good news, thanks.
