### ISSUE TITLE
CSS needs to be imported manually

### ISSUE THREAD

**Issue by maifeeulasad** [ruilisi/fortune-sheet#12]
**Describe the bug**
CSS needs to be imported manually

**To Reproduce**
Try this code:
```
import { Workbook } from "@fortune-sheet/react";
// try commenting the next line out
// import "@fortune-sheet/react/dist/index.css";

const App = () => {
  const x = 1;
  return (
    <div
      style={{
        width: "100%",
        height: "500px"
      }}
    >
      <Workbook
        data={[
          {
            name: "Empty",
            status: 1,
            celldata: [{ r: 0, c: 0, v: null }]
          }
        ]}
      />
    </div>
  );
};

export default App;

```

**Expected behavior**
Auto import or updated the docs(in readme)

**Screenshots**
<p align="center">
<kbd>

  <img src="https://user-images.githubusercontent.com/29339330/169682796-a1206957-b0ff-4b22-ab69-2c7e5216e0f5.png" alt="Without CSS importing UI remains broken"/>
</kbd>

</p>

**Additional context**
Codesandbox: https://codesandbox.io/s/playground-fortune-sheet-osbs0h?file=/src/App.tsx:0-478

**Comment by zyc9012** [comment]
Importing css is required
