### ISSUE TITLE
Limiting rows and columns are not working

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#120]
"row": 36, //the number of rows in a sheet
"column": 18, //the number of columns in a sheet

set the attributes as per the document https://ruilisi.github.io/fortune-sheet-docs/guide/sheet.html#initial
followed the above document
got more rows and columns
![image](https://user-images.githubusercontent.com/8638634/206527881-2e19f951-8bdf-4f65-b746-b22f0ec4c130.png)

**Comment by shuanhukexuejia** [comment]
Have fixed it, will commit it later

**Comment by gudipudipradeep** [comment]
@Qaplagzy  @shuanhukexuejia  is this changes are released as part of 0.11.0 version. because I couldn't see the reflection in 0.11.0

**Comment by shuanhukexuejia** [comment]
@gudipudipradeep 
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/84694078/209489409-f7570c65-b865-4467-9ff1-16491deae02f.png">
Try to create an empty sheet.

**Comment by gudipudipradeep** [comment]
@shuanhukexuejia  it working as you given but not working as sheet based configuration below.
`<Workbook  ref={workbookRef} data={data}  row={10} column={22} addRows={10} onOp={onOp} onChange={onChange} hooks={{ afterSelectionChange,}} />`

but not working as sheet based configuration as per the document. 
https://ruilisi.github.io/fortune-sheet-docs/guide/sheet.html#initial
like
`const settings =  [
{
    name: "Terminal",
    id: 0,
    status: 1,
	defaultRowHeight: 20,
	scrollLeft: 0,
	row: 20,
	column: 10,
	
  },
  {
	"name": "Calculation",
	"color": "",
	"id": "2",
	"status": 0,
	"order": 2,
	"celldata": [],
	"config": {},
	row: 10,
	column: 10,
  },
  {
	"name": "General",
	"color": "",
	"id": "3",
	"status": 0,
	"order": 2,
	"celldata": [],
	"config": {},
	row: 15,
	column: 30,
  }
 ];
 <Workbook  ref={workbookRef} data={data}  onOp={onOp} onChange={onChange} hooks={{ afterSelectionChange,}} />
`
It will helpful based on sheet based configuration.
