### ISSUE TITLE
configure readonly columns and cell request

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#121]
Please can some one guide how we can create readonly cell and columns.

Thanks for your help advance.

**Comment by shuanhukexuejia** [comment]
PROTECT WORKSHEET AND CONTENTS OF LOCKED CELLS is not supported temporarily, added to todo-list.

**Comment by nicoesiea** [comment]
There is an example here: https://github.com/ruilisi/fortune-sheet/issues/74
The variable is passed by: allowEdit:false,
and then, the value is used in the component to block the edition: allowEdit={props.allowEdit} 
Does it answer your question?

**Comment by gudipudipradeep** [comment]
@nicoesiea  I am looking for cell, columns and rows instead of sheet level.
