### ISSUE TITLE
guide on adding the custom component in toolbar

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#123]
![image](https://user-images.githubusercontent.com/8638634/206896954-30a105ed-9f1e-4d4f-900e-140f44923ecf.png)

like facebook, linkedin, twitter to share and logout button for business application.
for any custom actions it really help and value added feature if we can.

**Comment by hophacker** [comment]
Sure.

**Comment by shuanhukexuejia** [comment]
Added to todo-list. Time permitting, will try it

**Comment by jikoczl** [comment]
You can try to share your application, rather than share fortune-sheet.

**Comment by jikoczl** [comment]
As you can see, fb , linkedin or twitter is a business application. Fortune-sheet is a component for anyone's application.
Share or login/out should be put in your application, rather than a component.

**Comment by jikoczl** [comment]
Like google sheet, you can edit sheet or data in toolbar. Share/Login Button is in navbar.

**Comment by gudipudipradeep** [comment]
That's great, still if we can have option to add any custom things to toolbar will be nice because it might be best fit for the cases and scenarios.

**Comment by jikoczl** [comment]
That will be great if the thing added to toolbar is valuable for most people and fit for the component. Otherwise we should put anything into it just for someone's own case.

**Comment by gudipudipradeep** [comment]
@jikoczl your correct, but just I want to know the steps or method where we can modify or add our purpose.

**Comment by jikoczl** [comment]
> @jikoczl your correct, but just I want to know the steps or method where we can modify, extend or add the custom components or functionality for our purpose.

If the component or functionality is appropriate to put into sheet, you can give a PR of new feature. 
If the functionality is appropriate for your app, just put it into your app.

**Comment by gudipudipradeep** [comment]
@jikoczl right now I don't have any scenarios. Let see if anything in feature. If I or someone gets.

**Comment by roniemartinez** [comment]
Hello, I am also looking for this feature.

I am the author of Pulsars (https://github.com/roniemartinez/pulsars) which is a desktop spreadsheet application and I just migrated from `x-spreadsheet` to `fortune-sheet`.

One use-case is that "Open" and "Save" needs to be added in the toolbars. This existed in `x-spreadsheet` wherein you can extend the toolbars both at the start and end.

![image](https://user-images.githubusercontent.com/2573537/227781960-420e10cb-3c9e-4fad-aca1-0108bd787e7c.png)

I hope someone can provide a way to add a way to support this. Thanks!

**Comment by roniemartinez** [comment]
Thanks for implementing this! There is just 1 cosmetic bug I noticed on the tooltip. Please see https://github.com/ruilisi/fortune-sheet/issues/370

**Comment by gudipudipradeep** [comment]
@roniemartinez please can you tel me the steps to add the custom functionality.. By some example
I want to add some download functionality
It will be helpful..

**Comment by roniemartinez** [comment]
@gudipudipradeep I already commented on your query in https://github.com/ruilisi/fortune-sheet/issues/365#issuecomment-1537430422
