### ISSUE TITLE
In readonly mode, the cells used to create a function are not highlithed

### ISSUE THREAD

**Issue by nicoesiea** [ruilisi/fortune-sheet#127]
**Describe the bug**
When the file is displayed with **allowEdit** false, the cells used to create a function are not highlighted

**To Reproduce**
1. Load a file (in read-only mode) where one cell is created using a function: ![image](https://user-images.githubusercontent.com/4542315/207286641-dc75d914-7ce8-4c1f-8f40-4a8c21f8f2cd.png)
2. Select this cell
3. Observe the rendering, the cells B1 and B2 should be highlighted 

**Expected behavior**
Even in read-only mode, the cells should have their border in the color of the text (like it is without the read-only mode, like in Excel)
![image](https://user-images.githubusercontent.com/4542315/207287396-4384260f-508c-41fa-beb1-6811e35f7147.png)

**Screenshots**
Current rendering: ![image](https://user-images.githubusercontent.com/4542315/207286641-dc75d914-7ce8-4c1f-8f40-4a8c21f8f2cd.png)
Excepeted rendering: ![image](https://user-images.githubusercontent.com/4542315/207287396-4384260f-508c-41fa-beb1-6811e35f7147.png)

**Comment by shuanhukexuejia** [comment]
Sure, and there still some bugs in readonly mode eg. filter, insert image/link/formula still work. Will optimize it in the near future.

**Comment by nicoesiea** [comment]
Hello,
Testing the new 0.11.0 version, the highlight of the related formula cells is not existing in read-only mode.

**Comment by gazedreamily** [comment]
@nicoesiea cells referenced by formulas will only be highlighted when editing, but when it is readonly we can't edit it.

**Comment by nicoesiea** [comment]
Sure the request is not to edit the cell, when the user only selects the cell (click on the cell) it could be nice to add the highlight on the referred cells...
In the formula bar we can see the cell reference (letter + number) but it could be very nice to "see" them in the table too

**Comment by gazedreamily** [comment]
@nicoesiea hey, we've add this feature, you can just set `forceFormulaRef` to `true` to make the cell referred by formula.
By the way, we've created a community, you can [join us](https://discord.gg/vHGwMB77w5) and have a discussion!
