### ISSUE TITLE
Any guide on creating custom function

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#128]
Any guide to create custom function to call from cell like sum function
=sum(A1, B1)
Function or Formula.

**Comment by shuanhukexuejia** [comment]
Still not support custom function, will consider it

**Comment by gudipudipradeep** [comment]
@shuanhukexuejia  can you share your thoughts on custom function, guidance on high level to impalement and architecture feasibility for this request.

**Comment by gudipudipradeep** [comment]
@zyc9012  can we plan this action item if possible.
