### ISSUE TITLE
steps to setup development environment

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#131]
how to setup the development environment to customized or extend functionality. 
Please guide the steps after cloning this repo with some example to change the type script.

So that people can contribute and raise the pull request for bugs and importants. 

Development steps and guidelines, pull request standards. 

How to setup package folder contains core, formula and react to start and open basic sheet by importing modules, it will help.

**Comment by jikoczl** [comment]
To get the basic sheet, just see [Development](https://github.com/ruilisi/fortune-sheet#Development).
If you need local backend storage or want the edit sheet collabrately, you need a mongodb. see [backend](https://github.com/ruilisi/fortune-sheet#backend-storage-and-collabration)

**Comment by shuanhukexuejia** [comment]
@gudipudipradeep Are you working on this project? In this project, packages are managed by [Lerna](https://lerna.js.org/docs/getting-started) 
<img width="984" alt="image" src="https://user-images.githubusercontent.com/84694078/207845632-2a6f79d2-d983-4a79-a6b1-07c8b3d6e746.png">

**Comment by jikoczl** [comment]
https://assets.ruilisi.com/W0DUU83Beyfouo=CNLx5VA==
This is my screenshot for you to start the project from git clone to editing sheet

**Comment by jikoczl** [comment]
@gudipudipradeep
See this [screen shot](https://xiemala.com/s/B6fU54).
I will show you how to start the project from git clone to edit in sheet.

**Comment by gudipudipradeep** [comment]
@jikoczl thanks
