### ISSUE TITLE
Add default rows to add from configuration of sheet

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#134]
Pick number of rows for add button from default configuration. 
![IMG_20221219_000355](https://user-images.githubusercontent.com/8638634/208313626-8602e18f-94f7-44f1-bd49-05c200d2b77f.jpg)

Pic from configuration of sheet data. 
https://ruilisi.github.io/fortune-sheet-docs/guide/sheet.html

**Comment by Qaplagzy** [comment]
Yeah. Are you interested in doing this work? We will appreciate your contribution bro.

**Comment by gudipudipradeep** [comment]
@Qaplagzy  it is not allowing me to push the changes on feature branch. Need to have a write access for push the changes on new branch.

**Comment by jikoczl** [comment]
> @Qaplagzy it is not allowing me to push the changes on feature branch. Need to have a write access for push the changes on new branch.

You can give a pull request.

**Comment by jikoczl** [comment]
see [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) .

**Comment by gudipudipradeep** [comment]
@Qaplagzy  @shuanhukexuejia I took the latest package 0.12.0. But I couldn't my changes at addRows
``const settings = [
{
name: "General",
id: 0,
status: 1,
defaultRowHeight: 20,
scrollLeft: 0,
addRows: 10,
row: 20,
column: 10,
}
];
<Workbook ref={workbookRef} data={settings} onOp={onOp} onChange={onChange} hooks={{ afterSelectionChange,}} />`

did I miss anything, It worked in storybook.

**Comment by shuanhukexuejia** [comment]
Try in 0.12.3

**Comment by gudipudipradeep** [comment]
@shuanhukexuejia working as expected. we can close this.
