### ISSUE TITLE
Memory leak context menu 

### ISSUE THREAD

**Issue by kimgysen** [ruilisi/fortune-sheet#135]
**Describe the bug**
When clicking cells and calling the context menu on right-mouse click, the sandbox eventually crashes when repeating this step multiple times. 

**To Reproduce**
1. Go to ['sandbox'](https://codesandbox.io/s/playground-fortune-sheet-s8qxzz)
2. Left mouse click a cell+ right-mouse-click call context menu 
3. Left mouse click another cell+ right-mouse-click call context menu 
4. Repeat step 3 x-number of times (for me it happens at random, but you could try 10 - 30 times)
5. See error: 

![image](https://user-images.githubusercontent.com/4547364/208549785-bf363dfc-1a7c-4f9f-9ef8-d95b66ac885a.png)

**Expected behavior**
That the sandbox doesn't crash.

**Screenshots**
In my website stacktrace: 
![image](https://user-images.githubusercontent.com/4547364/208549928-afff8162-28b0-4060-b9b7-7746bf6b3b43.png)

**Additional context**
The strange thing is that this doesn't appear to occur in the StoryBook demo. 
Also note that right mouse clicking a cell (without left clicking it) doesn't 'select' a cell. 
The context menu appears without anything being selected, so it is unclear to what cell the context menu belongs to in this case.

**Comment by shuanhukexuejia** [comment]
* The issue of maximum update depth is strange, need some time to research.
* Will optimize the context menu, thanks for you report

**Comment by gazedreamily** [comment]
We hope our work on this issues can work correctly, just try our new versionWe hope our work on this issues can work correctly, just try our new version @kimgysen 
#142

**Comment by kimgysen** [comment]
@gazedreamily Is there going to be minor release version upgrade?

**Comment by gazedreamily** [comment]
The new version 0.11.0 has been released. 
By the way, I have tired fortune-sheet with source code in sandbox, and there won't cause the problem.
However, when I tried to import fortune-sheet as a model the problem could be reproduced.
We are still working on this.

**Comment by fantasticit** [comment]
update error occurs at react18.

**Comment by jikoczl** [comment]
New version 0.12.3 has been released. @kimgysen .  
Upgrade the fortunesheet version in sandbox. It seems that the problem won't appear again. If you still have the problem, contact us please.

**Comment by kimgysen** [comment]
@jikoczl Very interesting, I embedded this in my website and the problem appears to be solved. Many thanks ;-)
