### ISSUE TITLE
Options column, row, lang "zh_tw" are ignored

### ISSUE THREAD

**Issue by kimgysen** [ruilisi/fortune-sheet#136]
**Describe the bug**
Options column, row, lang "zh_tw" are ignored 

**To Reproduce**
1. Try to fill in any number for column or row, also set lang option "zh_tw"
2. Column / row count is still the default, despite options passed. Language zh_tw render English context menu 

**Expected behavior**
For the documented options to work as advertised. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4547364/208552429-f99b548a-338b-4966-812b-9bc657ce5260.png)

**Additional context**
I see that this sandbox uses an old version, but it's the same in the latest that I installed today.

**Comment by kimgysen** [comment]
`rowHeaderWidth` and `columnHeaderHeight ` don't appear to be doing anything either when changing the values. 
Setting the values to zero doesn't hide them.

**Comment by kimgysen** [comment]
I also think that the default fontSize has changed to 10 in the latest version from 11 in previous, so perhaps the docs need to be updated. 
I don't think that setting the defaultFontSize works either, unless I'm just doing a bunch of wrong things: 

![image](https://user-images.githubusercontent.com/4547364/208554721-17e779d4-6d56-491d-94fb-8a04664c1d22.png)


![image](https://user-images.githubusercontent.com/4547364/208554498-267300f4-18b1-4cff-9a22-bab87bc31313.png)

**Comment by jikoczl** [comment]
lang="zh-TW"

**Comment by shuanhukexuejia** [comment]
* The issue about row/column options has been fixed in #124 and it will work fine in next version
* Other config do have some problem, will look into it.

**Comment by shuanhukexuejia** [comment]
* fixed the issue of ```rowHeaderWidth/columnHeaderHeight``` in #141
