### ISSUE TITLE
onChange gets called on mount 

### ISSUE THREAD

**Issue by kimgysen** [ruilisi/fortune-sheet#147]
**Describe the bug**
onChange callback gets called on component mount. 

**To Reproduce**
1. Add onChange prop with console.log

**Expected behavior**
onChange gets called on data change. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4547364/209667502-16928988-b6d1-41a5-9875-071371a0fc24.png)

**Additional context**
Maybe this is not undesired, but when logging the callback on render in my demo tool, it is noticeable. 
In case it is desired behaviour this can be closed without further action, but maybe to be mentioned in the docs.

**Comment by Qaplagzy** [comment]
Thanks for reporting, we will mention it in the docs.
