### ISSUE TITLE
单元格选择框在特定情况下错位

### ISSUE THREAD

**Issue by bluesaiz** [ruilisi/fortune-sheet#15]
**Describe the bug**
在表格的最后几行进行编辑，然后按回车，重复上面的操作，直到选中的单元格超出可视区域，并继续重复操作，发现单元格选择框错位。

**Expected behavior**
单元格选择框正常

**Screenshots**
![image](https://user-images.githubusercontent.com/40681310/171073498-e6b8e9ea-d7ff-4114-8f87-7a793a964224.png)

**Comment by zyc9012** [comment]
感谢反馈
