### ISSUE TITLE
Getting additional space when hide the column and Scroll Bar

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#152]
![image](https://user-images.githubusercontent.com/8638634/209937833-b97d26e4-c65a-4800-a57d-80d78fc0c4d0.png)
at right side with scroll bar

**Comment by shuanhukexuejia** [comment]
How did you hide it

**Comment by gudipudipradeep** [comment]
@shuanhukexuejia under config we have an attribute.
"colhidden":{}, //hidden columns.
https://ruilisi.github.io/fortune-sheet-docs/guide/sheet.html#initial

**Comment by shuanhukexuejia** [comment]
Hide column has not been added, and how did you hide scrollbar

**Comment by gudipudipradeep** [comment]
@shuanhukexuejia  Just followed the document and hide the columns. after hiding my sheet fit for the screen but getting scrollbar at bottom and getting empty space after columns. instead of perfect fit

**Comment by shuanhukexuejia** [comment]
Ok, will look into it

**Comment by lvjing-tuzhi** [comment]
The function of hiding rows and columns has been supported, you are testing it

**Comment by gudipudipradeep** [comment]
@lvjing-tuzhi tested It is working as expected.
