### ISSUE TITLE
showFormulaBar 为 false时，输入=号报错

### ISSUE THREAD

**Issue by 553875193** [ruilisi/fortune-sheet#153]
https://github.com/ruilisi/fortune-sheet/blob/1c3bc76e450f4c3b577c1c324c69c0b7c47e38f5/packages/core/src/modules/formula.ts#L2556

当 showFormulaBar 为 false 时，<FxEditor />组件并没有被挂载，此时输入'='号时，给 FxEditor 组件的 innerHTML 赋值会出现错误，另外当 showFormulaBar 为 false 时，输入等号能否不要进入公式模式，这让用户很困扰

**Comment by shuanhukexuejia** [comment]
感谢反馈，将对这部分进行优化
