### ISSUE TITLE
Hidden column  not working while navigating from keyboard and cell size

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#154]
![image](https://user-images.githubusercontent.com/8638634/209963506-f33dc3e4-65b7-4796-918f-603c761badae.png)

If any hidden column in the middle of column sheet having impact on next column while navigating via keyboard and cell size is going showing wrong.

**Comment by shuanhukexuejia** [comment]
The function has not been added, it may because of the code in first migration, still need some work to complete it
