### ISSUE TITLE
Limiting rows and columns are not working as part of config

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#158]
it working as you given but not working as sheet based configuration below.
<Workbook  ref={workbookRef} data={data}  row={10} column={22} addRows={10} onOp={onOp} onChange={onChange} hooks={{ afterSelectionChange,}} />

but not working as sheet based configuration as per the document.
https://ruilisi.github.io/fortune-sheet-docs/guide/sheet.html#initial
like
`const settings = [
{
name: "Terminal",
id: 0,
status: 1,
defaultRowHeight: 20,
scrollLeft: 0,
row: 20,
column: 10,

},
{
"name": "Calculation",
"color": "",
"id": "2",
"status": 0,
"order": 2,
"celldata": [],
"config": {},
row: 10,
column: 10,
},
{
"name": "General",
"color": "",
"id": "3",
"status": 0,
"order": 2,
"celldata": [],
"config": {},
row: 15,
column: 30,
}
];
<Workbook ref={workbookRef} data={settings} onOp={onOp} onChange={onChange} hooks={{ afterSelectionChange,}} />
`
It will helpful based on sheet based configuration. Please can you conform once if I am wrong.

**Comment by shuanhukexuejia** [comment]
You're right, it doesn't work with sheet config, need optimization

**Comment by lvjing-tuzhi** [comment]
The problem has been solved
