### ISSUE TITLE
rowHeaderWidth和cellmainHeight不生效

### ISSUE THREAD

**Issue by 553875193** [ruilisi/fortune-sheet#159]
https://github.com/ruilisi/fortune-sheet/blob/1c3bc76e450f4c3b577c1c324c69c0b7c47e38f5/packages/react/src/components/SheetOverlay/RowHeader.tsx#L145

这里使用的是 context 中的 rowHeaderWidth，但是这里
https://github.com/ruilisi/fortune-sheet/blob/1c3bc76e450f4c3b577c1c324c69c0b7c47e38f5/packages/react/src/components/Workbook/index.tsx#L73
似乎只对 settings 做了对 props 的合并

**Comment by shuanhukexuejia** [comment]
目前cellmainHeight是无法设置的。rowHeaderWidth可以设置了，可在0.12.3版本中尝试

**Comment by 553875193** [comment]
> 目前cellmainHeight是无法设置的。rowHeaderWidth可以设置了，可在0.12.3版本中尝试

好的 感谢，然后问下可以设置表格内容的默认字体颜色吗

**Comment by shuanhukexuejia** [comment]
> > 目前cellmainHeight是无法设置的。rowHeaderWidth可以设置了，可在0.12.3版本中尝试
> 
> 好的 感谢，然后问下可以设置表格内容的默认字体颜色吗

目前只支持默认字体大小，后续可考虑加入更多默认设置
