### ISSUE TITLE
有打算做不同的ip同时操作协同文档的时候，显示不同的颜色

### ISSUE THREAD

**Issue by 1144075799** [ruilisi/fortune-sheet#16]
有打算做不同的ip同时操作协同文档的时候，显示不同的颜色

**Comment by Qaplagzy** [comment]
<img width="1106" alt="截屏2022-09-27 11 07 41" src="https://user-images.githubusercontent.com/44153730/192422731-404d8be0-5e5b-4894-8681-42e024862364.png">
