### ISSUE TITLE
devicePixelRatio seems to be ignored 

### ISSUE THREAD

**Issue by kimgysen** [ruilisi/fortune-sheet#167]
**Describe the bug**
The devicePixelRatio seems to be ignored 

**To Reproduce**
1. Add  devicePixelRatio prop
2. Set any number 

**Expected behavior**
Expecting to get some visual feedback when changing the value. 
(Also needs to work when the prop changes value) 

**Screenshots**
![image](https://user-images.githubusercontent.com/4547364/210171076-853f0101-b652-44ae-a12e-860b25357b0b.png)

**Comment by lvjing-tuzhi** [comment]
Right-clicking the menu will only bring up the functionality already done in the sheetTabContextMenu and cellContextMenu properties, and the display whitespace issue will be resolved.

**Comment by lvjing-tuzhi** [comment]
What do you want it to expect? Can you elaborate? devicePixelRatio is just the pixel ratio.

**Comment by kimgysen** [comment]
Hi, I've tried to update the prop, but when I log it out to the console, it seems that it stays 1: 

![image](https://user-images.githubusercontent.com/4547364/210345379-3ac2d2e7-fad6-4efc-adee-b49457b6d75e.png)

**Comment by lvjing-tuzhi** [comment]
Fixed a bug where the devicePixelRatio property was modified with no visual change. This property modification is to modify the ctx property of the table, thus modifying the table ui, but not modifying window.devicePixelRatio, so window.devicePixelRatio is unchanged, which is a normal phenomenon.

**Comment by kimgysen** [comment]
That makes sense. The lack of visual change was what I thought was strange. Thanks for having looked into this.
