### ISSUE TITLE
sheetTabContextMenu not respected 

### ISSUE THREAD

**Issue by kimgysen** [ruilisi/fortune-sheet#168]
**Describe the bug**
sheetTabContextMenu properties seem to be ignored. 

**To Reproduce**
1. Add custom menu as array of string values
2. Right mouse click a sheet tab 

**Expected behavior**
The context menu should appear 

**Screenshots**
![image](https://user-images.githubusercontent.com/4547364/210171906-3354f6e1-d57b-432f-9598-f32b2d57965e.png)

**Additional context**
cellContextMenu works partially (updating props changes the items) but also here I see that there no 1 - 1 correspondence, and the contextMenu even shows empty cells at the bottom of the contextMenu when propagating the changed array. 

![image](https://user-images.githubusercontent.com/4547364/210171958-aac37839-7e9c-49a9-aa92-666a7be72dc8.png)

**Comment by lvjing-tuzhi** [comment]
Right-clicking the menu will only bring up the functionality already done in the sheetTabContextMenu and cellContextMenu properties, and the display whitespace issue will be resolved.
