### ISSUE TITLE
👋❓ Use Auto-Fill / Drag Down Programmatically? 以编程方式使用自动填充/向下拖动？

### ISSUE THREAD

**Issue by firstredpepper** [ruilisi/fortune-sheet#17]
How can you drag down a range programmatically? I have a row that I wish to drag down and copy formats and formulas. Example below. Thank you!

如何以编程方式向下拖动范围？我有一行希望向下拖动并复制格式和公式。下面的例子。谢谢！

![image](https://user-images.githubusercontent.com/13411743/172421164-f1bc4ae4-89fd-4088-b51c-44bf55a8ab51.png)

![image](https://user-images.githubusercontent.com/13411743/172421186-d757766a-a22b-4f39-a999-d61b56826e97.png)

**Comment by firstredpepper** [comment]
This may already exist - I'm just asking how I can drag down a range in code? Thank you!

**Comment by zyc9012** [comment]
Thanks for your feature request, a new api for this will be available in the next release.

**Comment by firstredpepper** [comment]
Thanks @zyc9012 ! Do you know if there is a way to do this with luckysheet?

**Comment by zyc9012** [comment]
@firstredpepper Feature has been published in v0.5.7, please refer to https://ruilisi.github.io/fortune-sheet-demo/?path=/story/api--auto-fill-cell and https://github.com/ruilisi/fortune-sheet/blob/master/stories/API.stories.tsx#L126 for usage
