### ISSUE TITLE
请问支持xls，xlsm，csv格式吗

### ISSUE THREAD

**Issue by TreHack** [ruilisi/fortune-sheet#18]
lucky-sheet只支持xlsx格式的文件，其它格式都不支持，请问下fortune-sheet支持xls，xlsm，csv格式吗

**Comment by Qaplagzy** [comment]
你好 请问是在什么情况下支持这些格式 导入/导出吗

**Comment by sanchit3008** [comment]
https://github.com/Corbe30/FortuneExcel
