### ISSUE TITLE
setCellFormat ct value not applied

### ISSUE THREAD

**Issue by kimgysen** [ruilisi/fortune-sheet#182]
**Describe the bug**
When executing the setCellFormat api method, passing a configuration object for 'ct' (celltype), it doesn't appear to be applied. 

**To Reproduce**
1. Fill in for example 100 in cell (0, 0). 
2. Call for example: setCellFormat(0, 0, 'ct', {"fa": "0.0", "t": "n"}) 

**Expected behavior**
Expected the format to change to a one decimal number. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4547364/211403177-40163831-d6f3-44da-8773-76e6819c3a47.png)

**Additional context**
Apologies in case I misunderstood the api.

**Comment by gazedreamily** [comment]
We hope your problem will be fixed in #184 !
