### ISSUE TITLE
String arguments in formulas are mistaken for ranges

### ISSUE THREAD

**Issue by visualbasik** [ruilisi/fortune-sheet#196]
String arguments in quotation marks are sometimes mistaken for ranges (formula.ts -> getcellrange). In some examples this can trigger a seemingly endless loop in the formula calculation.

To recreate an 'endless loop' example:
    - (for some reason you must edit the formula text multiple times to trigger this.) 
1. Create a formula: =if("x",1,0)
2.  Edit the text argument of this formula in the formula bar from "x" to "InTheFirstHalfOf2022Year" 
3.  Edit the text argument of this formula in the formula bar from "x" to "InTheFirstHalfOf2022Year, xxxxx" 

For a fix, something like this seems to work:

export function getcellrange(ctx: Context, txt: string, formulaId?: string) {
  if (_.isNil(txt) || txt.length === 0) {
    return null;
   }

 ----->>>>>>   if (txt.substring(0, 1) == '"') return null;

**Comment by shuanhukexuejia** [comment]
Thanks for your report, will look into it. Or are you interested in doing this work(if time permitting)? We will appreciate your contribution bro.

**Comment by visualbasik** [comment]
In the future I would like to contribute. But for this particular issue, I don't fully understand the whole formula process, and it looks like there might be a larger issue here with how the formulas deal with ranges that I don't think I am qualified to solve. The immediate problem does go away if you institute my quick fix, but I don't really know if it's the 'right' solution.

**Comment by shuanhukexuejia** [comment]
Ok, then leave it to us

**Comment by gazedreamily** [comment]
@visualbasik 
Hey, I think your issue has been fixed in #201 . Thanks for you to help us improve our project!
