### ISSUE TITLE
showFormulaBar为false时在单元格上输入内容会报错

### ISSUE THREAD

**Issue by liangshuai** [ruilisi/fortune-sheet#21]
RT， `handleFormulaInput` 如下行会包 `Uncaught TypeError: Cannot read property 'id' of null`, 

https://github.com/ruilisi/fortune-sheet/blob/1cd2f5a9a38bbea0bc0aa7efc5b5809c81f8b28a/packages/core/src/modules/formula.ts#L2532

**Comment by Qaplagzy** [comment]
#25 感谢您的反馈！
