### ISSUE TITLE
Updated cell value is showing two times in onOp

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#211]
After updating the value it is showing two times in data object `{"op":"replace","value":"good","path":["data",7,0,"v"],"id":0}`

{"req":"op","data":[{"op":"replace","value":"good","path":["data",7,0,"m"],"id":0},{"op":"replace","value":{"fa":"General","t":"g"},"path":["data",7,0,"ct"],"id":0},{"op":"replace","value":"good","path":["data",7,0,"v"],"id":0}]}

And one more question How can identify the actual data that mean "good". because data object have 3 more objects and each object having value.

**Comment by shuanhukexuejia** [comment]
We use [produceWithPatches](https://immerjs.github.io/immer/patches) to record operations on data. In this example, the update func modifid m, ct, v of the cell[7,0], thus there were 3 ops. To identify the actual data, just check the object whose last element of path is "v".

**Comment by gudipudipradeep** [comment]
@shuanhukexuejia  am clear good...!
