### ISSUE TITLE
Formula parsing is not working for readonly rows and columns as background parsing activity

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#216]
Added config with following rows and columns as readonly with preconfigured formula as pre-loaded.

config: {colReadOnly:[3,7,10,14,19],rowReadOnly:[0]}
celldata:[{"r": 3,"c": 3,"v": {ct: {fa: "General", t: "n"},v: 0,m: "0", f:"=MULTIPLY(B4*C4)","ht":"0"},}]

tried both below items on readonly columns D.
D4=B4*C4 or D4=MULTIPLY(B4,C4)

**Comment by gudipudipradeep** [comment]
![image](https://user-images.githubusercontent.com/8638634/215551637-0f687aad-d84a-4ea6-8e88-dfc3b9c00bbe.png)
D4 having formula but not parsed for value.

**Comment by shuanhukexuejia** [comment]
Ok, will look into it.

**Comment by gazedreamily** [comment]
@gudipudipradeep could you tell us how you insert the data? We have tried to set cell value via setCellValue function in api, it performed well. We really recommend you to use it!

**Comment by gudipudipradeep** [comment]
@gazedreamily we are passing the data as an attribute workbook instance with following configuration as part of data.

config: {colReadOnly:[3,7,10,14,19],rowReadOnly:[0]}
celldata:[{"r": 3,"c": 3,"v": {ct: {fa: "General", t: "n"},v: 0,m: "0", f:"=MULTIPLY(B4*C4)","ht":"0"},}]

https://ruilisi.github.io/fortune-sheet-docs/guide/config.html
https://ruilisi.github.io/fortune-sheet-docs/guide/sheet.html

Please check above link how we are passing data for pre-configuration.

**Comment by gazedreamily** [comment]
@gudipudipradeep the v attr in config is the real value of the cell, the m attr is the value to be shown in the cell. If you set 0 to m, it will be shown as 0. Maybe you can use setCellValue function to set the formula to the cell, and it will calculate the target value by itself.

**Comment by gudipudipradeep** [comment]
@gazedreamily Yes, I understand that api call. but it is as part of configuration we need to do while loading.

**Comment by gazedreamily** [comment]
@gudipudipradeep Maybe you can try to remove v and m when you change any value used in the formula, the v and m value will be calculated by itself.

**Comment by gazedreamily** [comment]
@gudipudipradeep Maybe I can add an API to recalculate all formulas in the sheet so that you can call it to solve your problem?

**Comment by gudipudipradeep** [comment]
![image](https://user-images.githubusercontent.com/8638634/215828159-b8660891-3f1b-4f8b-9cb5-f89b5474d413.png)

showing empty after removing v and m values.
@gazedreamily  can you investigate the same thing by applying following configuration. you may can see actual problem from your end. I couldn't see any console logs also to identify the problem.

config: {colReadOnly:[3,7,10,14,19],rowReadOnly:[0]}
celldata:[{"r": 3,"c": 3,"v": {ct: {fa: "General", t: "n"},v: 0,m: "0", f:"=MULTIPLY(B4*C4)","ht":"0"},}]

**Comment by gudipudipradeep** [comment]
recalling the api also will not solve the problem seems to be. we need to check behavior for read-only columns and rows. some readonly functionality blocking actual formula calculation seems to be. may some experts are required to understand seems to be.

**Comment by gazedreamily** [comment]
@gudipudipradeep That is not an error, you have set the value m of the cell and the m will show in the cell. We are writing an api to recalculate all formula in the sheet. Maybe it will solve your problem.

**Comment by gudipudipradeep** [comment]
@gazedreamily  changed the cell value of C4 and  B4 as well from UI it is not re-calculating and other than readonly rows and columns are able to calculate the formula.

**Comment by gazedreamily** [comment]
@gudipudipradeep We think we have solved the problem. Try it!

**Comment by gudipudipradeep** [comment]
@gazedreamily  I will try. but formula isn't working for only readonly cells. for editable cells it is working as expected.

**Comment by gazedreamily** [comment]
@gudipudipradeep Sure, we will solve soon.

**Comment by gazedreamily** [comment]
@gudipudipradeep Call the recalculateAllFormula API when you import data with formula in it and then all formula will update automatically whether the cell is readonly or not!
