### ISSUE TITLE
Where we can check the fortune-sheet npm package version deployed for demo application.

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#224]
Where we can check the demo app deployed fortune-sheet npm package version..

**Comment by Qaplagzy** [comment]
hi, it usually should go with the latest release. You can check its npm package version [here](https://github.com/ruilisi/fortune-sheet-demo) by checking my commit message.
<img width="924" alt="截屏2023-02-02 12 45 02" src="https://user-images.githubusercontent.com/44153730/216233730-e9104a11-6d70-4cc7-87bd-d900253caa4a.png">

**Comment by gudipudipradeep** [comment]
@Qaplagzy Am asking for demo app npm package version..?
https://ruilisi.github.io/fortune-sheet-demo/?path=/story/features--basic

because it seems to bold deployment.

**Comment by shuanhukexuejia** [comment]
@gudipudipradeep its now the latest release

**Comment by gudipudipradeep** [comment]
@shuanhukexuejia thanks.
