### ISSUE TITLE
删除行或者列不会改变整个表格行列数量

### ISSUE THREAD

**Issue by jearyvon** [ruilisi/fortune-sheet#227]
**Describe the bug**
表格删除行或者列不会改变整个表格行列数量，demo中和实际使用中均可复现。
**To Reproduce**
1. 创建指定row和column的sheet(这里以9x9为例）
2. 选中一行或者一列
3. 右键删除选中行或者列
4. 发现表格仍然是原来样子（9x9）

**Comment by shuanhukexuejia** [comment]
感谢反馈，这边看到你已经提了一个pr，如果你有兴趣也可以assign给你来做，没时间的话就交给我们处理

**Comment by gazedreamily** [comment]
@jearyvon 您反馈的问题已经解决，感谢反馈！
