### ISSUE TITLE
当showFormulaBar为false时，编辑内容会报错

### ISSUE THREAD

**Issue by zackzergzeng** [ruilisi/fortune-sheet#23]
报错如下：
<img width="471" alt="image" src="https://user-images.githubusercontent.com/42129897/191432340-b2e68cb9-431b-4840-849a-f2d55dd5078a.png">
导致无法编辑了，看逻辑是$copyto因为没有formulabar所以值为空
<img width="457" alt="image" src="https://user-images.githubusercontent.com/42129897/191432671-14c532ce-c774-473f-96ec-f16739022b3a.png">

还有问下这个=开头自动变成公式的逻辑能否关闭？

**Comment by Qaplagzy** [comment]
你好，感谢反馈！
- bug会在近期统一修复并推新版本；
- =开头自动变成公式是主流的操作（numbers、Excel等），之后可以在设置里添加关闭选项

**Comment by Qaplagzy** [comment]
#25
