### ISSUE TITLE
Getting loading chunk error

### ISSUE THREAD

**Issue by Aafrin-Anjum** [ruilisi/fortune-sheet#236]
My webpack is picking esm.js file for the fortune-sheet package, which is giving me loading chunk error.

But When I am changing the file to umd.js manually  inside node modules fortune-sheet file it is working fine locally .
Looking for some solutions for this issue.

Below is the screen shot of the issue I am facing.
<img width="524" alt="image" src="https://user-images.githubusercontent.com/57133637/216608538-62051e82-293d-478a-b82a-875fc68a223b.png">

**Comment by shuanhukexuejia** [comment]
Sorry, have no idea about that. Haven't encountered this issue at present.

**Comment by gazedreamily** [comment]
@Aafrin-Anjum could you tell us which bowser do you use, and may be you can update to the latest version then have a try.

**Comment by sanchit3008** [comment]
^bump @gazedreamily

**Comment by sanchit3008** [comment]
closing as this isnt an issue with the library
