### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading '0')    

### ISSUE THREAD

**Issue by sandilya28** [ruilisi/fortune-sheet#237]
**Describe the bug**
The workbook is crashing when double-clicking on a cell, with the following stack trace

![Screenshot 2023-02-02 at 12 58 53 AM](https://user-images.githubusercontent.com/6747531/216143795-4eb0ed00-43db-4bc9-b4c3-03bf8d74096d.png)

**To Reproduce**
1. Go to the following [link](https://app-frontend-dsrpzqctwa-el.a.run.app/).
2. Add a Python cell from the bottom menu.
3. paste the following code
```
import pandas as pd

df = pd.DataFrame({"head": range(10), "body": range(10)})
df
```
4. Double-click on any cell
5. The web app crashes, **intermittently**, with the following stack trace
```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at handleCellAreaDoubleClick (index.esm.js:66450:1)
    at index.esm.js:2134:1
    at e.produce (immerClass.ts:94:1)
    at e.produceWithPatches (immerClass.ts:141:1)
    at index.esm.js:8604:1
    at basicStateReducer (react-dom.development.js:16540:1)
    at updateReducer (react-dom.development.js:16664:1)
    at updateState (react-dom.development.js:17004:1)
    at Object.useState (react-dom.development.js:17915:1)
    at useState (react.development.js:1622:1) 
```

**Screenshots**
![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/6747531/216825607-3b5582cc-57c9-44d1-827e-eef5d10955f8.gif)

**Comment by shuanhukexuejia** [comment]
https://user-images.githubusercontent.com/84694078/216884567-c278a053-2286-4964-81c4-8273e99bb10d.mp4

Didn't reproduce it

**Comment by sandilya28** [comment]
Thanks, @shuanhukexuejia for trying. Yeah, it's happening intermittently. I couldn't find out the pattern with which the crash was happening. I'll add more details when I find out.

**Comment by sandilya28** [comment]
One observation is when there multiple workbook instances, it's happening frequently. 
Could you please duplicate the cell with the same code and execute both cells and try.

**Comment by shuanhukexuejia** [comment]
> One observation is when there multiple workbook instances, it's happening frequently. Could you please duplicate the cell with the same code and execute both cells and try.

Have reproduced it, am looking into it

**Comment by shuanhukexuejia** [comment]
@sandilya28 you can try 0.14.0-beta.0 to see if recent update is related to this issue, just for eliminating the influence of it

**Comment by sandilya28** [comment]
I can see the issue on 0.14.0-beta.0, as well.

**Comment by shuanhukexuejia** [comment]
> I can see the issue on 0.14.0-beta.0, as well.

Ok, will continue to investigate

**Comment by shuanhukexuejia** [comment]
Try 0.14.0-beta.1  to see if it is solved

**Comment by sandilya28** [comment]
I guess, the `@fortune-sheet/core` package is still in `0.14.0-beta.0`, when I updated the `"@fortune-sheet/react": "0.14.0.beta-1"`

**Comment by shuanhukexuejia** [comment]
> I'm still seeing the issue. I guess, the `@fortune-sheet/core` package is still in `0.14.0-beta.0`, when I updated the `"@fortune-sheet/react": "0.14.0.beta-1"`

Ok, let me check

**Comment by shuanhukexuejia** [comment]
> I'm still seeing the issue. I guess, the `@fortune-sheet/core` package is still in `0.14.0-beta.0`, when I updated the `"@fortune-sheet/react": "0.14.0.beta-1"`

You're right, forgot the upate on `@fortune-sheet/core`, have updated it, you can try `0.14.0-beta.3` now.

**Comment by sandilya28** [comment]
Thanks, @shuanhukexuejia for quickly fixing this. Kudos to you.
