### ISSUE TITLE
NEW BUG INTRODUCED -> numeric function parameters are undefined

### ISSUE THREAD

**Issue by visualbasik** [ruilisi/fortune-sheet#240]
After your latest updates on Feb 5, it appears that all numeric function parameters are no longer being recognized. For example, the formula: **=sum(31,32)**  now calculates to zero instead of 63.  In the 'params' list in 'evaluate-by-operator.js these values all appear as 'undefined'
![image](https://user-images.githubusercontent.com/72219525/217024146-bc0818bd-643e-43dc-9e1d-1dbc9f602fcd.png)

**Comment by shuanhukexuejia** [comment]
Thanks for your report, fixed it in #241
