### ISSUE TITLE
无法build项目

### ISSUE THREAD

**Issue by jearyvon** [ruilisi/fortune-sheet#243]
**Describe the bug**
当`yarn build`的时候会报错 MacOS 和Window下均报错
``` shell
Error when using sourcemap for reporting an error: Can't resolve original location of error.

✖  error     Error: 'default' is not exported by ../../node_modules/dayjs/dayjs.min.js, imported by ../core/src/modules/validation.ts 
```

**To Reproduce**
复现步骤
1. clone项目
2. yarn install 安装依赖
3. yarn build 报错
4. yarn dev可以正常运行

**错误原因**
通过搜索引擎的帮助 猜测可能是rollup插件配置问题。
https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module
对`father-build`不熟悉。不知道项目作者怎么成功build的，难道是我的环境有问题。

```
电脑 1
OS  Mac OS 12.4 (intel)
node v16.13.2
yarn  1.22.10
电脑 2
OS window 10 
node v18.14.0
yarn  1.22.11
```
**Screenshots**
Mac OS 错误截图
<img width="995" alt="image" src="https://user-images.githubusercontent.com/12572920/217415963-0943ec31-1870-4d8a-b173-8145823c5a4c.png">

Window 错误截图

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/12572920/217416074-c7807b07-cd95-402b-913f-35e732baa6f1.png">

**Comment by shuanhukexuejia** [comment]
你好，可以再拉一下最新的代码，刚刚fix了, #242

**Comment by jearyvon** [comment]
> 你好，可以再拉一下最新的代码，刚刚fix了, 是跨package文件引用问题, #242

感谢已经解决
