### ISSUE TITLE
Formula calculation is not working for read only columns

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#245]
[screen-capture.webm](https://user-images.githubusercontent.com/8638634/217752265-5b030230-9595-4034-9e92-de9c0bef609a.webm)

working if we edit the formula. having some inconsistency problem seem to be.

D column is readonly.
config: {colReadOnly:[3,7,10,14,19],rowReadOnly:[0]}
celldata:[{"r": 3,"c": 3,"v": {ct: {fa: "General", t: "n"},v: 0,m: "0", f:"=MULTIPLY(B4*C4)","ht":"0"},}]

**Comment by gazedreamily** [comment]
@gudipudipradeep this is the same issues as you've feedback to us before.Please call calculateSheetFromula api to recalc all formula then the cells with formula in it will be update automatically.

**Comment by gudipudipradeep** [comment]
@gazedreamily can call api same as below or need to pass any mandatory argument Please let me know how we can pass those as well.

`workbookRef.current?.calculateSheetFromula()`

**Comment by gazedreamily** [comment]
@gudipudipradeep maybe you can try workbookRef.current?.calculateFormula(). This function takes no argument.

**Comment by gazedreamily** [comment]
@gudipudipradeep you can get more information about calcChain by https://github.com/gazedreamily/fortune-sheet/blob/master/docs/guide/sheet.md

**Comment by gudipudipradeep** [comment]
@gazedreamily even after calling that function also not working.

**Comment by gudipudipradeep** [comment]
@gazedreamily calculation also not happening in the demo formula menu as well.
https://github.com/ruilisi/fortune-sheet/blob/master/stories/data/formula.ts

**Comment by gazedreamily** [comment]
@gudipudipradeep maybe there's something wrong with some formula like INDIRECT the basic functions in formula sheet are right.

**Comment by gudipudipradeep** [comment]
I checked this formula this not working after changing the value.
 "=SUBTOTAL(9,OFFSET(E15,ROW(E15:E18)-ROW(E15),1,3))"

**Comment by gudipudipradeep** [comment]
Even after calling workbookRef.current?.calculateSheetFromula() this function  multiplication is not worked as per the shared clip snippet above.

**Comment by gudipudipradeep** [comment]
@gazedreamily spend some amount of time finally calcChain. help me to solve the issue.

**Comment by gazedreamily** [comment]
@gudipudipradeep Maybe there's something wrong with some of the formulas. You can tell us which formula can't work well and we will look into it soon! Thanks

**Comment by gudipudipradeep** [comment]
@gazedreamily sure will create other thread. closing the scope of the thread.
