### ISSUE TITLE
撤销(undo)快捷键无法撤销

### ISSUE THREAD

**Issue by jearyvon** [ruilisi/fortune-sheet#246]
**Describe the bug**
操作表格然后试用`ctrl+z`或者`command + z`撤销操作结果不生效。
点击顶部工具条撤销生效。
debug排查 `handleUndo` 方法都能正常调用。
快捷键撤销执行`handleUndo`中的`setContext`好像数据并没有更新到context上，校验了下`newContext`数据值的内容是正确的

排查的文件和对应行数如下：
`packages/react/src/components/Workbook/index.tsx 264:43`

**Comment by shuanhukexuejia** [comment]
感谢反馈，经调研，失效原因为嵌套的`setState`: `handleUndo/handleRedo`里有一次`setState`，`handleGlobalKeyDown`外又有一次，而`handleUndo/handleRedo`是在`handleGlobalKeyDown`里被调用的，里面对`context`的修改被外面的给覆盖了，故在调用`handleUndo/handleRedo`的地方加`setTimeout`将其放入queue以便在`handleGlobalKeyDown`外一层`setState`结束后触发调用

**Comment by shuanhukexuejia** [comment]
感谢反馈，目前本地调试是有这个问题。
这个问题比较奇怪，在[沙盒](https://codesandbox.io/s/epic-stonebraker-bt7qrz?file=/src/App.tsx)里`ctrl/command + z`是可以的(`command + shift + z`还是有问题)，本地另起一个demo又是失效的。
需要进一步调研。

**Comment by Qaplagzy** [comment]
solved by @zyc9012 🍺
