### ISSUE TITLE
How to import and export excel file

### ISSUE THREAD

**Issue by Deuscx** [ruilisi/fortune-sheet#273]
**Describe the solution you'd like**
new api like https://github.com/dream-num/Luckyexcel `transformExcelToLucky`

**Describe alternatives you've considered**

**Additional context**

**Comment by shuanhukexuejia** [comment]
Still not support import/export excel. But data structure is mostly compatible with Luckysheet, you can use transformExcelToLucky (some fields may need additional processing).

**Comment by jmptrader** [comment]
When you expect have support to Excel import and export ?

**Comment by shuanhukexuejia** [comment]
@jmptrader  we expect to finish it this month

**Comment by Akxe** [comment]
@shuanhukexuejia I don't want to rush you. But, do you know, when the import/export of Excel files could be ready?

**Comment by seleckis** [comment]
Still no progress on this?

**Comment by sanchit3008** [comment]
https://github.com/Corbe30/FortuneExcel
