### ISSUE TITLE
Paste at multi instance: impossible to paste to second instance

### ISSUE THREAD

**Issue by ents** [ruilisi/fortune-sheet#276]
**Describe the bug**
In case of multi instance impossible to paste to second instance. Pasting affect first instance, even if I clicked to second instance last time

**To Reproduce**
1. Go to https://ruilisi.github.io/fortune-sheet-demo/?path=/story/features--multi-instance
2. Copy any string to buffer (ctrl+C)
3. Click on any cell of first instance, and any cell of second instance after it
4. Press [ctrl]+[v]
5. See error: value will be pasted to first instance, not second one

**Expected behavior**
Value is pasted to last selected instance

**Comment by shuanhukexuejia** [comment]
Thanks for your report, will look into it

**Comment by gazedreamily** [comment]
@ents We have fixed this problem in version 0.15.0. Have a try!
