### ISSUE TITLE
表格没有渲染出来

### ISSUE THREAD

**Issue by chopin406** [ruilisi/fortune-sheet#296]
**Describe the bug**
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/7414914/224952273-bb795eeb-3d3c-4cc8-bdca-7fef9aa478a4.png">
这个示例，没有表格内容，我在本地安装fortune-sheet后，也展示不出表格内容出来。
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by shuanhukexuejia** [comment]
你好，请问是所有features都不显示吗，线上demo是显示的

**Comment by chopin406** [comment]
<img width="1636" alt="image" src="https://user-images.githubusercontent.com/7414914/226091254-0f70016c-063b-4fff-9399-d569a1bd6278.png">

所有features都不显示
我的谷歌浏览器版本：版本 110.0.5481.177（正式版本） (x86_64)

**Comment by shuanhukexuejia** [comment]
你本地运行右边就有这么多tab？还是做了什么改动，左边的tab右边应该一次只显示一个，你可以在
<img width="681" alt="image" src="https://user-images.githubusercontent.com/84694078/226226224-cdcb4ce7-8a73-463f-a5c2-2b670ab20736.png">
这个文件里把数据log一下，看一下有没有什么问题

**Comment by shuanhukexuejia** [comment]
你好，这是storybook docs里没给workbook的容器添加高度导致的，切至Canvas tab即可正常显示，若需要docs tab也显示出来，可以将这里的容器高度改为固定值
<img width="824" alt="image" src="https://user-images.githubusercontent.com/84694078/226548082-6d05ec8f-f009-41dc-92e8-0330dd576391.png">
