### ISSUE TITLE
Merge config is not parsing the data

### ISSUE THREAD

**Issue by RobPando** [ruilisi/fortune-sheet#299]
**Describe the bug**
If `config.merge` is added to the initial sheet it is ignored completely and the out put renders as if there is none.

**To Reproduce**
1. On initial sheet add any correct data to the config merge object
2. Does render accordingly

**Expected behavior**
When I set the initial `config.merge` of any sheet it should render the data correctly such as
```javascript
sheet.config.merge = {
  "29_6": {
      "r": 29,
      "c": 6,
      "rs": 2,
      "cs": 6
  },
  "1_1": {
      "r": 1,
      "c": 1,
      "rs": 2,
      "cs": 10
  },
  "4_6": {
      "r": 4,
      "c": 6,
      "rs": 1,
      "cs": 6
  },
  "5_2": {
      "r": 5,
      "c": 2,
      "rs": 1,
      "cs": 2
  },
  "7_6": {
      "r": 7,
      "c": 6,
      "rs": 1,
      "cs": 6
  },
  "8_9": {
      "r": 8,
      "c": 9,
      "rs": 16,
      "cs": 1
  },
  "25_1": {
      "r": 25,
      "c": 1,
      "rs": 3,
      "cs": 4
  },
  "25_6": {
      "r": 25,
      "c": 6,
      "rs": 3,
      "cs": 6
  }
}
```

**Comment by gazedreamily** [comment]
@RobPando the v porp of cells in merge range should has mc porp and it value is the same like data in config.merge.
For example, v in the first block will like this in the range of merge cell area.
```
v : {
      "r": 29,
      "c": 6,
      "rs": 2,
      "cs": 6
  }
```

**Comment by RobPando** [comment]
@gazedreamily  I just tried that and it doesn't work, I checked out what the library is doing with the data and it seems like it sets ur correctly but does not display merged this is the data that the library converts it to when I pass to `celldata` data that should be merged:  
<img width="285" alt="Screenshot 2023-03-15 at 12 34 32 PM" src="https://user-images.githubusercontent.com/20132181/225394737-9a97aaee-91b3-4343-b428-dd853249f20c.png">

I then saw what the library does to the data when I manually do it on the rendered sheet and it displays it like so:
<img width="264" alt="Screenshot 2023-03-15 at 12 44 29 PM" src="https://user-images.githubusercontent.com/20132181/225397212-8ea30a9f-51ea-47f0-a76a-a658d001ca96.png">

So I tried this in the cellmate cells in merge range:
```javascript
{
r: 1,
c: 2,
v: { mc: {r: 1, c: 1}}
}
```

and I actually get the library data to parse correctly or at least exactly how it would if I merge the cells manually but I get a `Main merge info is null` for clarity I am also still passing `config: {merge` data correctly. Furthermore, once I have this data if I try to merge manually I get `index.esm.js?4254:57818 Uncaught TypeError: Cannot convert undefined or null to object
    at mergeCells` 
<img width="1543" alt="Screenshot 2023-03-15 at 12 47 11 PM" src="https://user-images.githubusercontent.com/20132181/225397866-e17f385a-3709-4de1-b135-0bb22186fa9e.png">

any help would be appreciated it please. Thank you!!

**Comment by gazedreamily** [comment]
@RobPando both data and config should contain the info of mergecell

**Comment by gazedreamily** [comment]
@RobPando I've merged cells form c3 to e6
<img width="639" alt="image" src="https://user-images.githubusercontent.com/82332499/225511092-34be4249-aa72-4788-9d76-18ef344fe1df.png">
And the data value will like this
<img width="645" alt="image" src="https://user-images.githubusercontent.com/82332499/225511385-8694069e-3c34-4fa3-8dca-5a1307884fb5.png">
Only the value of c3 cell has "rs" and "rc".
the config will like this
<img width="189" alt="image" src="https://user-images.githubusercontent.com/82332499/225511555-774e5d44-134c-4a7b-92bc-d6c342bf38f4.png">
