### ISSUE TITLE
Copy-paste from Google sheet

### ISSUE THREAD

**Issue by mougrim** [ruilisi/fortune-sheet#3]
Hi, thanks for the react implementation.

I used demo https://ruilisi.github.io/fortune-sheet-demo/?path=/story/workbook--basic and as I see copy-paste range doesn't work from Google sheet.
I see it in formula, but cells don't be updated:
![Screenshot_20220408_122034](https://user-images.githubusercontent.com/1057709/162406395-257ae7c5-a463-4ba6-9a0b-f474173a623b.png)

**Comment by zyc9012** [comment]
@mougrim Thanks for your feedback, we will look into this issue.

**Comment by carl-jin** [comment]
google sheet copy 出来的内容会存在一个 html 格式的代码，需要识别后进行转换才能得知每个单元格的内容。
看看这个 [https://github.com/carl-jin/gs-clipboard/blob/main/src/GsClipboard/parser/GoogleSheetParser.ts](https://github.com/carl-jin/gs-clipboard/blob/main/src/GsClipboard/parser/GoogleSheetParser.ts)

**Comment by zyc9012** [comment]
Fixed and online demo updated

**Comment by mougrim** [comment]
Many thanks!
