### ISSUE TITLE
collabration 是如何解决两个用户操作冲突的

### ISSUE THREAD

**Issue by klsqmadi** [ruilisi/fortune-sheet#308]
我目前只能在 ```stories\Collabration.stories.tsx``` 看到 ```WebSocket``` 监听事件，通过 ```applyOp``` 进行 setCellValue

**Comment by klsqmadi** [comment]
好像是没有解决是吗，我在本地开了两个表格试了下

**Comment by gazedreamily** [comment]
@klsqmadi collabration是当一位用户进行操作时，会将用户操作转化为op并使用websocket对其它客户端通信，其它客户端收到op后会进行相应更改

**Comment by klsqmadi** [comment]
@gazedreamily 
但是如果两个用户(A, B)同时编辑同一个单元格(insert)，用户A先应用自己的 op1 ，然后应用用户B的 op2。
用户A 的 op1 岂不是被 op2 覆盖了，如何解决这个问题？

**Comment by klsqmadi** [comment]
我在网上看到看到的是通过操作转换 OT 来解决，这个库好像没有这个操作

**Comment by gazedreamily** [comment]
@klsqmadi 如果两个人同时更改某个单元格的同一个属性，后来的更改会覆盖之前的更改

**Comment by klsqmadi** [comment]
@gazedreamily fortune-sheet 未来有计划来解决这个问题吗

**Comment by gazedreamily** [comment]
暂时没有这样的计划

**Comment by gazedreamily** [comment]
@klsqmadi 想请问一下，这边需要怎么样的效果呢？比如说A删除了某个单元格的内容，并更改为了自己想要的内容，B此时添加了内容，那么应该需要保留怎么样的结果呢？

**Comment by klsqmadi** [comment]
@gazedreamily 
比如A，B同时编辑单元格C1（12345），A 在 C1 插入 6（123456）生成 op1，B 在 C1 插入 7 生成（123457）生成 op2。
A 应用 op1 后应用 op2
预想：A（1234567）
实际：A （123457）
原因：因为 op2 是一个 replace op, 会将 op1 修改的内容进行覆盖

**Comment by gazedreamily** [comment]
@klsqmadi 
如果A，B同时编辑，那么无论结果是1234567还是1234576感觉都会很奇怪
从整体视角，可能是更能体现协同编辑特性
但是从A、B各自的视角，则是自己编辑的内容被污染了，由于这一级协同的存在，A与B都无法改出自己想要的结果
所以我们还是更倾向于将单元格的属性作为原子，而不是属性的内容作为原子，而单元格的内容也是一个单元格属性

**Comment by klsqmadi** [comment]
@gazedreamily 在服务器看来是 A 先发出的 op，所以 B 的内容应该也是 1234567，B 向服务器发出 op2 之前应该先向服务器确认自己是否是最新的版本，如果不是的话应该从服务器拉取最新的版本，然后基于最新的版本去生成 op2`（123456 + 7）

**Comment by gazedreamily** [comment]
@klsqmadi 我的意思是，从服务器或者整体视角来看，确实是这样
但是，如果单从A的视角或B的视角来看的话，就是自己正在编辑的数据被污染了
无论如何A和B都改不到自己想要的数据

**Comment by gazedreamily** [comment]
@klsqmadi 请问问题解决了嘛？

**Comment by klsqmadi** [comment]
@gazedreamily 当然

**Comment by HengCC** [comment]
@gazedreamily  其实这个在业界有相应的模型来解决这样的问题. 现在的协作模型在协作上确实有致命问题.  我之前用luckysheet实现了这样的协作在实际应用中会出现数据覆盖.  当然你们这里讨论的只局限在一个单元格. 但是当范围扩大到选区或者整个表格的时候. 比如你修改了A. 但是其他用户进行了排序. 你修改的单元格可能就变成排序后的单元格了.  整体来看. 确实需要一个模型来解决这种协作合并问题.  可以看下OT或者CRDT.  CRDT目前有比较好的开源方案.  [YJS](https://docs.yjs.dev/)

**Comment by dwzkit** [comment]
YJS是我目前在基于Prosemirror开发的项目上使用的，效果还比较稳定，也建议涉及到多人协同的部分，可以考虑一下YJS
