### ISSUE TITLE
[Bug Report]: 使用vite时，提示 Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by Deuscx** [ruilisi/fortune-sheet#315]
**Describe the bug**
版本0.15.3， 复现链接 https://codesandbox.io/p/sandbox/pensive-frog-9tq71o?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A22%2C%22endLineNumber%22%3A4%2C%22startColumn%22%3A22%2C%22startLineNumber%22%3A4%7D%5D

**Screenshots**
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/48537979/227904510-9b8f812d-0661-4f19-817c-64c81b45c71d.png">

**Comment by shuanhukexuejia** [comment]
goole一下报错，加个配置就好了
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/84694078/228107542-6191a723-184d-4e12-89ea-c35428f03959.png">
看起来root样式还有些问题，应该不是fortune-sheet的问题，对vite不太熟悉了

**Comment by Deuscx** [comment]
感谢 可以了。请教下，这里用global而不是globalThis的原因是什么呢?

**Comment by shuanhukexuejia** [comment]
> 感谢 可以了。请教下，这里用global而不是globalThis的原因是什么呢?

google出来的几个方案，这个我也没仔细研究，两个都work

**Comment by zyc9012** [comment]
@Deuscx Changed to `globalThis` here: https://github.com/ruilisi/fortune-sheet/commit/2b5aaae5f9de41ef5427481885ed0c37e47bac3c. (not released yet)
