### ISSUE TITLE
协同编辑下，插入图片无法正常同步

### ISSUE THREAD

**Issue by XieRenbing** [ruilisi/fortune-sheet#316]
**Describe the bug**
协同编辑下，插入图片无法正常同步

**To Reproduce**
1、同时开启两个页面编辑表格内容
2、在一个页面表格中插入图片
3、本页面图片插入成功，另一个页面，拿到了op数据，applyOp后没有同步成功

**Expected behavior**
图片插入后，能正常同步

**Screenshots**
![image](https://user-images.githubusercontent.com/51075684/227956945-43e13dbb-cd7c-4d9d-a9e3-ff518bb6b971.png)

**Additional context**
上面截图中的图片数据在应用applyOp后无法展示图片

**Comment by gazedreamily** [comment]
方便提供一下浏览器版本、项目版本等更详细的信息吗
我这边测试未能复现

**Comment by XieRenbing** [comment]
> 方便提供一下浏览器版本、项目版本等更详细的信息吗 我这边测试未能复现
项目版本:     "@fortune-sheet/core": "^0.15.3",  "@fortune-sheet/react": "^0.15.3",
浏览器版本：google chrome  版本 111.0.5563.111（正式版本） （64 位）

**Comment by gazedreamily** [comment]
同一台机器上打开了两个窗口进行测试的吗

**Comment by XieRenbing** [comment]
是的，同一台机器的同一个浏览器开了两个页面操作的

**Comment by gazedreamily** [comment]
后端是用的什么呢？

**Comment by XieRenbing** [comment]
使用的 "@hocuspocus/server": "1.0.0-beta.6",

**Comment by gazedreamily** [comment]
后端在对op进行处理的时候，是否参考了项目中backend-demo内对op的处理
这个项目内的op处理以及分发都是通过后端与前端的websocket通信来实现的
