### ISSUE TITLE
Copy Paste is not working in Safari

### ISSUE THREAD

**Issue by tianqiwuben** [ruilisi/fortune-sheet#325]
**Describe the bug**
Copy Paste is not working in Safari

**To Reproduce**
Open demo in Safari, try copy / paste, nothing happen

**Comment by gazedreamily** [comment]
Sure, we'll look into it.

**Comment by tianqiwuben** [comment]
@gazedreamily we are really impressed by your work and would love to connect to see if we can work together? Would you please book a meeting [here](https://calendly.com/ben-wtq/30min) or send your available time to ben@turbolayer.com for a 15min talk? Thank you so much!

**Comment by gazedreamily** [comment]
@tianqiwuben we've created a server in discord, welcome to have a chat!
https://discord.gg/vHGwMB77w5
I think we are in different time zones!
