### ISSUE TITLE
yarn build时出现TypeError: fs.rmSync is not a function错误

### ISSUE THREAD

**Issue by rayblade** [ruilisi/fortune-sheet#33]
fortune-sheet 版本 0.6.3
yarn build时出现TypeError: fs.rmSync is not a function错误

`@fortune-sheet/react: Build umd success entry: src/index.ts
@fortune-sheet/react: Build cjs with rollup
end value has mixed support, consider using flex-end instead
@fortune-sheet/react: Build cjs success entry: src/index.ts
@fortune-sheet/react: Build esm with rollup
end value has mixed support, consider using flex-end instead
@fortune-sheet/react: Build esm success entry: src/index.ts
/fortunesheet/scripts/build.js:22
fs.rmSync("packages/core/tsconfig.json");
   ^

TypeError: fs.rmSync is not a function
    at Object.<anonymous> (/fortunesheet/scripts/build.js:22:4)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

yarn的版本为：1.22.19

**Comment by jikoczl** [comment]
我也1.22.19，我没问题

**Comment by jikoczl** [comment]
> fortune-sheet 版本 0.6.3 yarn build时出现TypeError: fs.rmSync is not a function错误
> 
> `@fortune-sheet/react: Build umd success entry: src/index.ts @fortune-sheet/react: Build cjs with rollup end value has mixed support, consider using flex-end instead @fortune-sheet/react: Build cjs success entry: src/index.ts @fortune-sheet/react: Build esm with rollup end value has mixed support, consider using flex-end instead @fortune-sheet/react: Build esm success entry: src/index.ts /fortunesheet/scripts/build.js:22 fs.rmSync("packages/core/tsconfig.json"); ^
> 
> TypeError: fs.rmSync is not a function at Object. (/fortunesheet/scripts/build.js:22:4) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) at internal/main/run_main_module.js:17:47 error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
> 
> yarn的版本为：1.22.19

我也1.22.19，我没问题
