### ISSUE TITLE
allowEdit:false is not working on 0.16.0 version

### ISSUE THREAD

**Issue by Bryanlhx** [ruilisi/fortune-sheet#341]
when upgrade fortune-sheet from 0.15.3 to 0.16.0, allowEdit:false is not working anymore, 
although, allowEdit=false in setting, but the excel is still editable, can change/delete the value on excel
any workaround solution to make excel readonly?

**Comment by shuanhukexuejia** [comment]
Fixed in 0.16.1, you can try it
