### ISSUE TITLE
Calculations with decimal places in a cell

### ISSUE THREAD

**Issue by jonasrht** [ruilisi/fortune-sheet#343]
**Describe the bug**
When attempting to perform calculations involving decimal places in a cell, an #ERROR! is returned, indicating incorrect behavior.

**To Reproduce**
1. Go to the "Demo" page.
2. Click on a cell to activate it.
3. Enter the formula "=100*0.8".
4. See the #ERROR! result.

**Screenshots**
![fortune-sheet-bug](https://user-images.githubusercontent.com/45701283/232227063-0006ecbc-58d2-4254-bc33-e68508297283.png)

**Expected Behavior:**
The calculation "=100*0.8" should yield the correct result without any errors.

**Comment by gazedreamily** [comment]
sure, we will look into it
