### ISSUE TITLE
allowEdit===false, still can delete value by clicking filter icon

### ISSUE THREAD

**Issue by Bryanlhx** [ruilisi/fortune-sheet#349]
allowEdit===false, still can delete value by clicking filter icon
clicking filter icon will popup a window,  there is delete function on popup window
let's say, click the filter icon near by B column,

![image](https://user-images.githubusercontent.com/8220327/232689772-92bd7c00-aa0b-4d5d-bd87-29674a4bf4a8.png)

![image](https://user-images.githubusercontent.com/8220327/232689697-d37a19a3-f584-4655-9ff2-564694d1f539.png)

**Comment by shuanhukexuejia** [comment]
Thanks for your report, will fix it soon

**Comment by Bryanlhx** [comment]
Hi,when you will release it?

**Comment by gazedreamily** [comment]
@Bryanlhx will release this week.

**Comment by Bryanlhx** [comment]
is it released?

**Comment by shuanhukexuejia** [comment]
@Bryanlhx 0.17.0 has been released, you can try it now
