### ISSUE TITLE
Sorting does not adjust cell ranges

### ISSUE THREAD

**Issue by visualbasik** [ruilisi/fortune-sheet#363]
when you sort a range of cells, if one of the columns contains a formula with a cell reference to another cell within that range, the cell reference needs to be adjusted for its new position in the sort.

for example:
col1     col2      col2

after sorting you get:

1            2      =sum(a2,b2)
4            1      =sum(a3,b3)
7            3      =sum(a1,b1)

INSTEAD OF:
1            2      =sum(a1,b1)
4            1      =sum(a2,b2)
7            3      =sum(a3,b3)

**Comment by ZhengIce** [comment]
Thank you for your attention. I apologize for the bad experience I provided, but the example you gave was not accurate enough for me to understand your intention. Could you please explain the details of this issue again or clarify what effect you want to achieve?

**Comment by ZhengIce** [comment]
@visualbasik Thank you for your attention. I apologize for the bad experience I provided, but the example you gave was not accurate enough for me to understand your intention. Could you please explain the details of this issue again or clarify what effect you want to achieve?

**Comment by visualbasik** [comment]
Thank you for looking at this. The issue is fairly basic. Any time a cell moves location…for example, if you cut and paste, or if you sort….the expected behavior is that any reference to that cell will update to the new location. 

 

So, for a very simple example: Type ‘=A1’ into cell B1. Now, ‘cut’ cell A1, and paste it to A2. You will see that cell B1 still says ‘=A1’. Whereas if you do the same thing in excel or Google sheets, it will update to say ‘=A2’

 

Alex

**Comment by ZhengIce** [comment]
@visualbasik We apologize for the negative experience and have taken note of the issue. We will work to fix it as soon as possible. Thank you for your feedback.

**Comment by ZhengIce** [comment]
The bug has been fixed and will be updated shortly.

**Comment by visualbasik** [comment]
Thank you!

Is there any plan to allow a user to choose which column to sort on? That
would be a very helpful feature.

Alex

**Comment by ZhengIce** [comment]
Already in the future development plans
