### ISSUE TITLE
Hot to add customToolbarItems by example in demo-site

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#365]
Please can you share the example to add an item to the custom toolbar with some functionality in demo site.
<img width="947" alt="image" src="https://user-images.githubusercontent.com/8638634/235639531-9780890f-0088-43b7-8012-ffd291d1e583.png">
toolbar button with small functionality like while clicking on that button it has show the current selected cell value like that.

I have see below pr. but I couldn't catch.
https://github.com/ruilisi/fortune-sheet/pull/322/files#diff-dbb374fe62f23fdf770022c3b44c4d1d8ffbe3b81c6678a4f3e06ae045ebf83e

**Comment by gudipudipradeep** [comment]
#123 looking some example to implement.

**Comment by roniemartinez** [comment]
@gudipudipradeep You can check my implementation here:

https://github.com/roniemartinez/pulsars/blob/54b36272cbf771be737c465a3c5e22de1187a548/src/App.jsx#L9-L51

Notice that when using SVG's you need to set the width and the height to 24 or else you will not see anything
