### ISSUE TITLE
How can I make a particular cell of sheet as non-editable ? 

### ISSUE THREAD

**Issue by Aafrin-Anjum** [ruilisi/fortune-sheet#368]
My Requirement is to make some cells in the sheet as non-editable on the basis of certain conditions ,
Any solution on how to achieve this ?

**Comment by architmmmec** [comment]
@zyc9012, can you help here?

**Comment by gazedreamily** [comment]
Storry, still not support for it

**Comment by architmmmec** [comment]
Any idea when it will be done @gazedreamily ?

**Comment by sanchit3008** [comment]
fixed
