### ISSUE TITLE
公式：IF(D1=0,0,C1/D1)，当D1为0时，会显示DIV/0的Error

### ISSUE THREAD

**Issue by kilik52** [ruilisi/fortune-sheet#37]
**Describe the bug**
公式：IF(D1=0,0,C1/D1)，当D1为0时，会显示DIV/0的Error

**To Reproduce**
1. Go to [online demo](https://ruilisi.github.io/fortune-sheet-demo)
2. 找个空白的单元格
3. 输入公式：=IF(D1=0,0,C1/D1)
4. 单元格会显示#DIV/0 !

**Expected behavior**
应该结果为0

**Screenshots**

<img width="530" alt="截屏2022-10-06 13 36 11" src="https://user-images.githubusercontent.com/37238/194222658-dbf56ea8-edb4-4bea-8ffb-6b3adbd641c1.png">

**Comment by jikoczl** [comment]
公式库问题，已加入TODO-LIST

**Comment by Qaplagzy** [comment]
已解决
