### ISSUE TITLE
[Custom toolbar] Tooltip z-index should be higher

### ISSUE THREAD

**Issue by roniemartinez** [ruilisi/fortune-sheet#370]
**Describe the bug**
Toolbar tooltip has a lower z-index

**To Reproduce**
Implement the custom toolbar feature: https://github.com/ruilisi/fortune-sheet/issues/123

**Expected behavior**
Proper z-index

**Screenshots**
See the "Open" tooltip
![image](https://user-images.githubusercontent.com/2573537/236678043-5d16d9ea-7ca7-45d4-adc0-498db60f5bde.png)

**Additional context**
This is used in Pulsars: https://github.com/roniemartinez/pulsars/blob/master/src/App.jsx

**Comment by gudipudipradeep** [comment]
@roniemartinez how to svg path at end of the toolbar or middle of the toolbar. 
Means path tag of svg

**Comment by roniemartinez** [comment]
@gudipudipradeep It is not supported. You should open a new issue for that. I think you should ask the maintainers.

**Comment by gazedreamily** [comment]
@roniemartinez it has been fixed and will be released soon!
