### ISSUE TITLE
For pre populated formula, values are not getting updated

### ISSUE THREAD

**Issue by architmmmec** [ruilisi/fortune-sheet#374]
Hi Team, There is a formula on Sum(H15)  which uses cells from D15-D18, Now when I am changing the value of D15 cell, sum value is not getting updated.. Can you help here.. This is a basic sheet functionality
![Screenshot_2023-05-08_at_2 19 25_PM](https://github.com/ruilisi/fortune-sheet/assets/37949198/bd86c96a-5cea-47b8-b578-6f6da70fa2c3)

**Comment by architmmmec** [comment]
@zyc9012, can you help here

**Comment by architmmmec** [comment]
@gazedreamily , when can we expect it to be fixed?

**Comment by architmmmec** [comment]
@gazedreamily, Without offset formula also we are facing the same issue. If we are changing the formula then its value is getting updated but dependent columns on this column are not getting updated

**Comment by gazedreamily** [comment]
@architmmmec which formula refers to other formula？

**Comment by architmmmec** [comment]
@gazedreamily , lets say we have a formula on column AZ: SUM(AX:AY) and  BA is dependent on AZ, if AZ formula is getting updated then corresponding value of BA is not getting updated accordingly.
