### ISSUE TITLE
One more formula reference issue - cut and paste

### ISSUE THREAD

**Issue by visualbasik** [ruilisi/fortune-sheet#377]
If you cut a cell which contains a parameter for a function, and paste it into another cell, the formula reference does not update.

For example:
put: 1 in cell A1
put: 2 in cell A2
put =sum(A1,A2) in cell A3
If you cut cell A1 and paste it to B1, the expected result would be for the formula to update to: =sum(B1,A2)

**Comment by sanchit3008** [comment]
Even in Excel, cutting A1 and pasting it to B1 does not update the function to `SUM(B1,A2)`. Closing this.

**Comment by visualbasik** [comment]
Very sorry…I used an incorrect example. I will reopen with the correct information. 

 

Alex
