### ISSUE TITLE
请问react版本如何手动调用calculateFormula？

### ISSUE THREAD

**Issue by kilik52** [ruilisi/fortune-sheet#38]
sheet在创建的时候设置了一些公式，但是在第一次显示时不会自动计算。我看doc里面有一个叫workbook.calculateFormula的，但是在ref里面没找到。

**Comment by Qaplagzy** [comment]
感谢反馈！

这里尚未实现，文档迁移中的疏漏，后续更新中会增加这部分功能，以及对doc进一步梳理。

**Comment by gazedreamily** [comment]
@kilik52 已经完成了相关API
