### ISSUE TITLE
ScrollLeft not working for the sheet.

### ISSUE THREAD

**Issue by Aafrin-Anjum** [ruilisi/fortune-sheet#385]
I am trying to set the left and right scroll bar position through **ScrollLeft** property . But the the scroll bar is starting  with 0 position only.

Can you please help me here...

**Comment by architmmmec** [comment]
@gazedreamily, can you help here

**Comment by architmmmec** [comment]
@zyc9012, can you help here, this is critical for us

**Comment by gazedreamily** [comment]
@architmmmec @Aafrin-Anjum we will look into it soon

**Comment by architmmmec** [comment]
@gazedreamily , is there a workaround for this? When can we expect this to be fixed?
It is a blocker for us

**Comment by gazedreamily** [comment]
@architmmmec maybe this API can help you https://github.com/ruilisi/fortune-sheet/blob/master/docs/guide/api.md#scroll

**Comment by sanchit3008** [comment]
@gazedreamily can close this one as well
