### ISSUE TITLE
Updating the Worksheet celldata results in infinite loop

### ISSUE THREAD

**Issue by Aafrin-Anjum** [ruilisi/fortune-sheet#386]
On 'onChange' I am calling a function in which a backend API is getting called where the new data for the sheet is fetched, when I am setting the fetched data to **data** property of Worksheet then **onChange** property is getting called again which is resulting in infinite loop...
Any solution for this ?

**Comment by architmmmec** [comment]
@gazedreamily, can you help here?

**Comment by gazedreamily** [comment]
Sure, we will look into it

**Comment by gazedreamily** [comment]
> On 'onChange' I am calling a function in which a backend API is getting called where the new data for the sheet is fetched, when I am setting the fetched data to **data** property of Worksheet then **onChange** property is getting called again which is resulting in infinite loop... Any solution for this ?

Could you tell us what you do in the onchange function?

**Comment by Aafrin-Anjum** [comment]
In onChange function I am calling the backend API where I am sending the sheet data and the response which I am getting from the backend , I am setting it to state which I am passing to data property of the worksheet.

**Comment by gazedreamily** [comment]
@Aafrin-Anjum do you change the data of sheet in onChange function?

**Comment by sanchit3008** [comment]
This can be closed now @gazedreamily
