### ISSUE TITLE
Add more row not working

### ISSUE THREAD

**Issue by dinhchien-zps** [ruilisi/fortune-sheet#388]
Hey guys, in the v0.17.0 @fortune-sheet/react, when i click to the add more row button, it not working. v0.13.0 still works

**Comment by ZhengIce** [comment]
@dinhchien-zps Could you provide more information? In my testing, I did not observe this situation.

**Comment by dinhchien-zps** [comment]
I just realized maybe this error is not of fortune-sheet. The error appeared when I cloned the (https://github.com/electron-vite/electron-vite-react) repo and used fortune-sheet v0.17.0. When I just use fortune-sheet v0.17.0 the error does not appear. Maybe the error is due to the incompatibility of the 2 libraries.

**Comment by ZhengIce** [comment]
@dinhchien-zps  I don't have much knowledge about vite, so we are unable to provide assistance at the moment.

**Comment by dinhchien-zps** [comment]
@ZhengIce I found the reason why the error happened. The error occurs because in the file index.html there is a (<meta
      http-equiv="Content-Security-Policy"
      content="script-src 'self' 'unsafe-inline';" />) tag. Thanks for the support.

**Comment by dinhchien-zps** [comment]
@ZhengIce I found the reason why the error happened. The error occurs because in the file index.html there is a 
```html
<meta
      http-equiv="Content-Security-Policy"
      content="script-src 'self' 'unsafe-inline';" />
```
tag. Thanks for the support.

**Comment by ZhengIce** [comment]
Congratulations to you
