### ISSUE TITLE
Highlighted cell movement bug with frozen rows/columns

### ISSUE THREAD

**Issue by sanchit3008** [ruilisi/fortune-sheet#391]
**Describe the bug**
If some rows and/or columns are frozen, then moving the highlighted cell using arrow keys causes the correct cell to be selected but the sheet view doesn't auto scroll.

**To Reproduce**
1. Open a sheet with frozen rows (say 2)
2. Scroll down a lot and select a cell in say row 30
3. Now press up arrow to move upwards

**Expected behavior**
The non-frozen view should scroll when the highlighted cell is beyond the viewing range.

**Screenshots**
![image](https://github.com/ruilisi/fortune-sheet/assets/22197708/18d2c520-fabb-49ac-8b41-0119c1fb6019)

Notice the disparity between cell selected and the sheet view.

**Comment by architmmmec** [comment]
@zyc9012 / @gazedreamily  can you help here?
