### ISSUE TITLE
Border issue

### ISSUE THREAD

**Issue by dtiwarii** [ruilisi/fortune-sheet#392]
1-We are getting error "cfg.borderInfo.push is not a function" when trying to apply border to selected cells.
2- How to restrict maximum number of rows and columns 
 Can you Please Help.

**Comment by gazedreamily** [comment]
@dtiwarii is there any step about how to reproduce that？
And there is a limitation of 10000 rows and 1000 columns which can not be customized.

**Comment by dtiwarii** [comment]
> @dtiwarii is there any step about how to reproduce that？ And there is a limitation of 10000 rows and 1000 columns which can not be customized.

steps - 
1- Select Multiple cells 
2- Go to toolbar and click on border button It will throw this error.

**Comment by gazedreamily** [comment]
> > @dtiwarii is there any step about how to reproduce that？ And there is a limitation of 10000 rows and 1000 columns which can not be customized.
> 
> steps - 1- Select Multiple cells 2- Go to toolbar and click on border button It will throw this error.

Is there some special steps? We can not reproduce that.

https://github.com/ruilisi/fortune-sheet/assets/82332499/1a58135b-4a24-4b1d-95ad-8b2a1644aa3b

**Comment by dtiwarii** [comment]
> > > @dtiwarii is there any step about how to reproduce that？ And there is a limitation of 10000 rows and 1000 columns which can not be customized.
> > 
> > 
> > steps - 1- Select Multiple cells 2- Go to toolbar and click on border button It will throw this error.
> 
> Is there some special steps? We can not reproduce that.
> 
>  QQ20230601-192750-HD.mp4

I initialise config.borderInfo =[] instead of {}. This solved above error but now i have one more issue in fortune-sheet demo also this issue is there -
We are not able to border left line of first column, right line of last column ,
top line of first row , bottom line of last row.Attached screenshot below.
<img width="838" alt="Screenshot 2023-06-02 at 11 13 13 PM" src="https://github.com/ruilisi/fortune-sheet/assets/46244026/d53c26d9-a371-4c56-9d04-49278d256247">
 Please fix this issues asap. Thank

**Comment by gazedreamily** [comment]
@dtiwarii this is not a bug. To facilitate easy identification of row and column labels, the leftmost and top borders are not rendered, although they do exist. Google sheet and Excel also employ the same approach.

**Comment by dtiwarii** [comment]
> @dtiwarii this is not a bug. To facilitate easy identification of row and column labels, the leftmost and top borders are not rendered, although they do exist. Google sheet and Excel also employ the same approach.

Is there anyway we can achieve this outside the framework(without doing changes to framework).?

**Comment by gazedreamily** [comment]
> > @dtiwarii this is not a bug. To facilitate easy identification of row and column labels, the leftmost and top borders are not rendered, although they do exist. Google sheet and Excel also employ the same approach.
> 
> Is there anyway we can achieve this outside the framework(without doing changes to framework).?


Currently, this feature is not available temporarily.

**Comment by dtiwarii** [comment]
> > > @dtiwarii this is not a bug. To facilitate easy identification of row and column labels, the leftmost and top borders are not rendered, although they do exist. Google sheet and Excel also employ the same approach.
> > 
> > 
> > Is there anyway we can achieve this outside the framework(without doing changes to framework).?
> 
> Currently, this feature is not available temporarily.

In our case we need this functionality can you please help us to achieve this ...?

**Comment by blu3gui7ar** [comment]
Similar issue when pasting. Suspicious code is here:
https://github.com/ruilisi/fortune-sheet/blob/3a0a0ad40a38f8e931fc7f5069964dcecaaae93b/packages/core/src/events/paste.ts#L1669

borderInfo should be array instead of object which has no 'push' method.

<img width="1381" alt="image" src="https://github.com/ruilisi/fortune-sheet/assets/2851963/8e99de1d-9e48-47af-a746-a58a4612044b">
<img width="466" alt="image" src="https://github.com/ruilisi/fortune-sheet/assets/2851963/1bf3685c-b84a-4c90-b503-64345f891527">
