### ISSUE TITLE
Text in cell area loses sharpness on a high browser zoom level.

### ISSUE THREAD

**Issue by flashtheman** [ruilisi/fortune-sheet#4]
**Describe the bug**
When zooming user browser zoom in Chrome, text rendering becomes blurry.

**To Reproduce**
Zoom in the browser to about 160% zoom level.

**Comment by zyc9012** [comment]
@flashtheman Thanks for your report, we will look into this.

**Comment by nicoesiea** [comment]
I confirm the bug, with zoom 175% here is the display:
![image](https://user-images.githubusercontent.com/4542315/204556231-112e5e6c-432c-4a5d-b9bd-3975a5460a94.png)

And here is the view in edition mode (same zoom)
![image](https://user-images.githubusercontent.com/4542315/204556155-d25524a4-fb46-40ff-ad92-ad89e898a53e.png)

**Comment by lvjing-tuzhi** [comment]
The problem has been solved
