### ISSUE TITLE
authority sheet not working

### ISSUE THREAD

**Issue by baian1** [ruilisi/fortune-sheet#418]
1. 受保护模式下，表格依旧可以编辑
```ts
const data = {
  name: "protected",
  config: {
    authority: {
      sheet: 1,
    },
  },
  celldata: [
    { r: 0, c: 0, v: { v: "can edit", lo: 0 } },
    { r: 0, c: 1, v: { v: "is locked", lo: 1 } },
    { r: 0, c: 2, v: { v: "default", lo: 1 } },
  ],
};
```
![image](https://github.com/ruilisi/fortune-sheet/assets/43271479/8648eb44-a3ff-402b-8db5-09168edf9f75)

2. readonly row，在表格中不能编辑，输入框中可以编辑
![image](https://github.com/ruilisi/fortune-sheet/assets/43271479/f30e3a81-250e-4c42-b5fd-3291aed3c116)

**Comment by juanparati** [comment]
As an alternative workround in case that you want to protect a specific row or column you can use rowReadOnly or colReadOnly config property.

Example:

```
config: {
            rowReadOnly: {},
            colReadOnly: {
                "0": true, // Protect first column
                "1": true, // Protect second column
                "2": true // Protect third column
            }
        }
...
```
