### ISSUE TITLE
Filtering hides frozen rows

### ISSUE THREAD

**Issue by sanchit3008** [ruilisi/fortune-sheet#422]
**Describe the bug**
When a column wise filter is applied, it even hides the frozen rows which shouldnt be the case. Only non-frozen items should be filtered.

**To Reproduce**
1. Go to a sheet with frozen rows (https://ruilisi.github.io/fortune-sheet-demo/?path=/story/features--freeze)
2. Apple a filter to say Column A with values 5 and 6.
3. Notice that only one frozen row is visible now.

**Expected behavior**
Non frozen rows should get filtered, frozen ones should remain as it is.

**Screenshots**

- Before filter 
<img width="468" alt="image" src="https://github.com/ruilisi/fortune-sheet/assets/22197708/32c72198-21f4-41a0-aba2-0e2b920fdb4a">

- After filter is applied with. values 5 and 6
<img width="471" alt="image" src="https://github.com/ruilisi/fortune-sheet/assets/22197708/97cd2558-65dc-4491-8fc6-e4d4bc9284a7">

**Comment by ZhengIce** [comment]
@sanchit3008 This might not be a problem, as Google Sheets also adopts a similar strategy.
