### ISSUE TITLE
Use Github Sponsors for donation

### ISSUE THREAD

**Issue by Akxe** [ruilisi/fortune-sheet#429]
**Is your feature request related to a problem? Please describe.**

I would like to see an option for sponsoring this project.

**Describe the solution you'd like**
Given this project is hosted on Github, the GitHub sponsors is an easy option.

**Describe alternatives you've considered**
I don't want to message authors and collaborators to give each money... Also, I need to fill VAT correctly.

**Additional context**
...

**Comment by Qaplagzy** [comment]
Thank you very much for your support. #431

**Comment by Akxe** [comment]
Through Patreon, I can give you a small donation on my personal behalf, but if you were to create [GitHub Sponsors](https://github.com/sponsors), I could possibly issue some money from the company.

-----

May I ask, when the import/export might be done/in preview?

**Comment by sanchit3008** [comment]
@zyc9012 lets close this in case gh sponsors wont be used?
