### ISSUE TITLE
lo:0 Cannot prohibit modifying cells

### ISSUE THREAD

**Issue by Rio-shuai** [ruilisi/fortune-sheet#446]
data:[
    { 
   ...
       celldata:[ { r:0 ，c:0, v:{ m:'name' ， v:'name' , lo:0  } }] 
   }
]

**Comment by Rio-shuai** [comment]
What I want is that this initialized cell cannot be modified @zhcalvin

**Comment by gazedreamily** [comment]
@Rio-shuai it is implemented by #421

**Comment by sanchit3008** [comment]
closing this as the feature is available in current versions
