### ISSUE TITLE
updateSheet props not working

### ISSUE THREAD

**Issue by ozlemkcr** [ruilisi/fortune-sheet#448]
The updateSheet function is not working.

1. Rendering the Workbook
2. When I give an example sheet data to the updateSheet function, it does not set (it works when I give the data normally, so the data is not wrong)

Normally when I use this function it should render the whole sheet (according to the api document)

![image](https://github.com/ruilisi/fortune-sheet/assets/48884511/202ba499-cdf9-4122-9e7e-c53d3ff6cdfd)
![image](https://github.com/ruilisi/fortune-sheet/assets/48884511/4de72f0a-6dac-4d7a-8a89-f11bbf699e84)
 using:
![image](https://github.com/ruilisi/fortune-sheet/assets/48884511/14ae51c9-206b-46cc-b2b9-dec924a07182)

**Comment by sanchit3008** [comment]
have you ensured that `celldata` which is being passed in the second `useEffect` is an array? (as you are manually putting it inside an array in `Workbook` props)

**Comment by guiziii** [comment]
@ozlemkcr i needed to do something like https://github.com/ruilisi/fortune-sheet/issues/451 to get it to work

**Comment by ozlemkcr** [comment]
@sanchit3008 thank you, i fixed. @guiziii thank you for your solution i will try but i want to set all sheet property. In the development environment, `useEffect `is triggered twice and the `updateSheet `function crashes. I didn't have such a problem with the `applyOp `function. Do you have any knowledge about this issue??

Errors:
![image](https://github.com/ruilisi/fortune-sheet/assets/48884511/d2608ee1-73cd-45aa-94bd-bfa94155f37d)

![image](https://github.com/ruilisi/fortune-sheet/assets/48884511/a28d9b3c-5604-40e5-a8b4-b5ba8256ac6f)

**Comment by sanchit3008** [comment]
Can you post your updated code? Not sure if I am following what the exact problem is now.

**Comment by ozlemkcr** [comment]
Of course, I am sure that the data is correct because when I trigger the same action with the button it works.

![image](https://github.com/ruilisi/fortune-sheet/assets/48884511/83160196-8625-4f43-8b17-f568918c2320)

**Comment by sanchit3008** [comment]
closing this as this is not a fortune sheet issue, please follow the suggestions posted by @guiziii in #451
