### ISSUE TITLE
为什么右键点击之后的菜单位置会偏离鼠标位置很多

### ISSUE THREAD

**Issue by stoneyallen** [ruilisi/fortune-sheet#450]

**Comment by stoneyallen** [comment]
![image](https://github.com/ruilisi/fortune-sheet/assets/5013633/ae4d0344-2f95-491a-8941-ade5cb5c2bac)

**Comment by ZhengIce** [comment]
@stoneyallen 你好，请问你使用什么框架引用的

**Comment by gazedreamily** [comment]
@stoneyallen 将在 #469 中修复

**Comment by sanchit3008** [comment]
was fixed
