### ISSUE TITLE
Valid date cell value (yyyy-MM-dd) is replaced by value "1900-01-00"

### ISSUE THREAD

**Issue by juanparati** [ruilisi/fortune-sheet#454]
**Describe the bug**
When a cell formatted as "date" has valid date like "2023-04-01" (yyyy-MM-dd) is automatically transformed into "1900-01-00".

**To Reproduce**
1. Select a cell
2. Format the cell as "Date" type
3. Type a valid date that uses the format yyyy-MM-dd like for examle "2023-01-01"
4. Press enter

**Expected behavior**
The typed date correctly set.

**Screenshots**
![wrong_date_format](https://github.com/ruilisi/fortune-sheet/assets/835173/36c3763d-e9df-45c3-9f2c-91cc0e42d9c4)

**Comment by gazedreamily** [comment]
@juanparati may be fixed with #474
