### ISSUE TITLE
Summing two read only cell into a target readonly cell value not updating

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#455]
M5(cell)=C5+K5

C, K are readolny cells. Value are not updating into M5 readonly cell.
I tried to add **calcChain** even it is not working.
calcChain=[{"r":5,"c":5,"id":0}, {"r":5,"c":5,"id":0}, ]

**Comment by gazedreamily** [comment]
@gudipudipradeep if C, K is readonly and M5 is refer to them, C, K will not change and M5 will not update. Can you please provide more details?

**Comment by gazedreamily** [comment]
@gudipudipradeep If they are readonly, the formula will not update. The formula will not re-caculate while initing. You can put the value in that cell.

**Comment by gudipudipradeep** [comment]
Because some time dats will update from background. 
Need to have update option to do automatically

**Comment by gudipudipradeep** [comment]
I have done different way. It worked. 
We can close. 
@gazedreamily

**Comment by gazedreamily** [comment]
> I have done different way. It worked. We can close. @gazedreamily

sure
