### ISSUE TITLE
enable onOp option to capture the changes for the specific columns 

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#456]
Enable onOp to capture the changes of specific column instead of all columns.

  async onOp(op: Op[]){
	console.log(this.instruments);
    console.log(JSON.stringify({ req: "op", data: op }));
  };

enable the specific columns improve the number of iteration inside the code and improve performance. instead of hitting all columns to identify.

**Comment by gudipudipradeep** [comment]
I tried with extending library, but not able extend the functionality due to const.
<img width="961" alt="image" src="https://github.com/ruilisi/fortune-sheet/assets/8638634/26135939-d48f-4f6d-b2a8-65b09f198b90">

this.workbookRef.emitOp = this.emitOp.bind(this);

  async emitOp(ctx, patches, options, undo) {
	console.log("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------");
 };

**Comment by sanchit3008** [comment]
this is a non-issue, and applies to a specific use case. it should be left to the user implementation to ignore an op on the rows/cols then want.
