### ISSUE TITLE
select the cell by using api

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#464]
select the cell by using api, need a api select the cell for quick movement instead of cell.

**Comment by gazedreamily** [comment]
@gudipudipradeep you can just use this api
https://ruilisi.github.io/fortune-sheet-demo/?path=/story/api--set-selection

**Comment by gudipudipradeep** [comment]
@gazedreamily  How we can make sure as part of sheet loading as selected column. like open any excel sheet first column as selected column

**Comment by gazedreamily** [comment]
@gudipudipradeep Sorry, I can't understand it

**Comment by gudipudipradeep** [comment]
we close this. @gazedreamily
