### ISSUE TITLE
Is it possible to use this library in vanilla js without React nor Vue ?

### ISSUE THREAD

**Issue by abenhamdine** [ruilisi/fortune-sheet#471]
**Describe the bug**

Perhaps it's a documentation bug : I don't see any explanations how to install and use this library without React.
However the React integration seems to be a separate package.
Is that possible to use it without React ? As a plain js library ?
If yes, how to install it and initialize it ?

**To Reproduce**

Read the readme and the website and look for installation usage without React

**Expected behavior**

A brief explanation for how to install it without React
For comparison, Luckysheet has an explanation and an example for that.

**Comment by gazedreamily** [comment]
still not support

**Comment by KiddoV** [comment]
I thought this [@fortune-sheet/core](https://www.npmjs.com/package/@fortune-sheet/core) will support non-React app, I was wrong :(.

**Comment by KiddoV** [comment]
I see this issue is closed. Is it support yet?

**Comment by sanchit3008** [comment]
officially we dont support it yet, i have closed it because this is a duplicate issue https://github.com/ruilisi/fortune-sheet/issues/74
