### ISSUE TITLE
enable onOp option to capture the changes old and new value

### ISSUE THREAD

**Issue by gudipudipradeep** [ruilisi/fortune-sheet#477]
enable onOp option to capture the changes of old and new value to analysis.

**Comment by gazedreamily** [comment]
The `op` is to represent a step what the value changes to. It is not a change process but an action.

**Comment by gudipudipradeep** [comment]
@gazedreamily in op we can able to see the changed value but not old value. Like
Old: 5
New: 8
So that it will be clear to know for auditing and making some decision.
