### ISSUE TITLE
Cell formatting is not being applied to text, after inline text editing

### ISSUE THREAD

**Issue by seleckis** [ruilisi/fortune-sheet#480]
**Describe the bug**
When part of text is being styled then the formatting of the cell is not being applied

**To Reproduce**
1. Add some text to cell
2. Change text size to e.g. 24
3. Select a part of text
4. Change formatting to e.g. bold
5. Select another cell

**Expected behavior**
Text remains of size 24.

**Actual result**
Text changes its size to default 10.

https://github.com/ruilisi/fortune-sheet/assets/988504/bf32c113-d589-4bfe-8137-d58cc84a8bff

**Comment by gazedreamily** [comment]
@seleckis This issue will be fixed in #481
