### ISSUE TITLE
Formula grammar online edit/test

### ISSUE THREAD

**Issue by mingodad** [ruilisi/fortune-sheet#487]
I've just added `grammar-parser.jison` to https://mingodad.github.io/parsertl-playground/playground/ an online `Yacc/Lex` compatible editor/tester (select `Fortnue sheet formula parser` from `Examples` then click `Parse` to see a parser tree for the content in `Input source` editor).

I hope it can help debug/develop/document/test the grammar from this project !

Any feedback is welcome !

**Comment by zyc9012** [comment]
Awesome! Thank you @mingodad
