### ISSUE TITLE
Read-only cell

### ISSUE THREAD

**Issue by TiagoBlauth** [ruilisi/fortune-sheet#494]
**Is your feature request related to a problem? Please describe.**
I want to have the ability to make some cells read-only.

**Describe the solution you'd like**
The solution would be an API to set a range of cells read-only, make all cells read-only, or make just a range of cells editable.

**Describe alternatives you've considered**
Make a sheet completely read-only.

**Additional context**
I want to share a sheet for a user who needs to fill a range of cells. They can create formulas, and copy and paste data, but there are some cells (row titles, column titles) they should not be able to change.

**Comment by sanchit3008** [comment]
I am currently marking each individual cell as locked instead of setting a range by checking if the cell exists inside the range i want to lock.

**Comment by sanchit3008** [comment]
This is possible by setting the `lo` property for a given cell to 0 or 1.
