### ISSUE TITLE
Undo operation after changing a cell with linked formulae does not change the cell itself

### ISSUE THREAD

**Issue by sanchit3008** [ruilisi/fortune-sheet#497]
**Describe the bug**
Undo operation after changing a cell with linked formulae does not change the cell itself

**To Reproduce**
1. Go to a cell on which other cell's formula is dependent
2. Change the value, the linked formula cell also changes
3. Perform 1 undo operation, the formula cell value revert but the original edited cell still remains unchanged

**Expected behavior**
Both the cell and the formula cells should revert with the same 1 undo operation

**Comment by zyc9012** [comment]
Yes, this is a known bug. Right now it requires 2 undos

**Comment by sanchit3008** [comment]
thakns for the update @zyc9012 , i will have a look at the pr too

**Comment by zyc9012** [comment]
I pushed a commit 42b3c22353556b3748278e03f0539dac22223552 which should resolve this issue

**Comment by sanchit3008** [comment]
I think this can be closed now
