### ISSUE TITLE
Suggestion, maybe you need Hyperformula

### ISSUE THREAD

**Issue by jmptrader** [ruilisi/fortune-sheet#5]
Excelent initiative, thank's for this.

You know that Formula Parser is deprecated, so may be you can consider integrate to Hyperformula component.

Hyperformula, is a complete, open-source Excel-like calculation engine written in TypeScript. Includes 380+ built-in functions. Maintained by the team at Handsontable.

https://github.com/handsontable/hyperformula/

Thank's a lot.

**Comment by zyc9012** [comment]
Thanks for your suggestion.

We do have considered Hyperformula, but it's API makes it harder to be integrated into this project currently, and it's code size seems to be a lot larger.

May be we will switch to Hyperformula after some rounds of refactors.

**Comment by jmptrader** [comment]
Thank's!

**Comment by marekgregor** [comment]
Hyperformula's license GPLv3 is not compatible with the MIT license of fortune-sheet. Moreover, GPLv3 in this project could be used only for [non-commercial or open-source use](https://handsontable.github.io/hyperformula/guide/licensing.html#available-licenses). Therefore, it directly collides with either MIT or plain GPLv3 licenses.

**Comment by Corbe30** [comment]
Hey @marekgregor , is "non-commercial or open-source use" an addition over the actual GPLv3 license? If so, can I not use Hyperformula with Fortunesheet in my org *internally*? (e.g. an internal tool used within the org). Just wanted to clearly understand it.
