### ISSUE TITLE
Adding support in the library for Finnish language

### ISSUE THREAD

**Issue by Juho-Korhonen** [ruilisi/fortune-sheet#502]
**Fortunesheet does not support the Finnish language.**
I work for a company which would be interested in using fortune-sheet, and having the functions (for example SUM) in Finnish.

I want to add support for the Finnish language, I will personally handle all translations to the locale and if fortune-sheet maintainers are interested in incorporating Finnish into the library, I will create a pull request.

Maintainers please let me know if you are interested in incorporating Finnish into the project.

I will not translate everything in locale but atleast the majority of the functions and a large part of the text.

**Comment by sanchit3008** [comment]
hi, thanks a lot for the suggestion. however, we wont be able to accommodate this request unless it is implemented end to end by the contributor. would you be willing to translate everything / add the option for finnish everywhere in the codebase?

**Comment by sanchit3008** [comment]
https://github.com/ruilisi/fortune-sheet/wiki/Adding-support-for-new-languages
