### ISSUE TITLE
Internal Error: fortune-sheet@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile

### ISSUE THREAD

**Issue by seleckis** [ruilisi/fortune-sheet#511]
Hi, fresh install does not allow to run `yarn dev`.

**To Reproduce**
1. Fork repository
2. git clone repository
3. `yarn install`
4. `yarn dev`
5. See error: 
```
yarn run v1.22.19
$ npx yarn storybook
Internal Error: fortune-sheet@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
```

**Expected behavior**
Working dev mode

**Additional context**
I have tried to remove all lock files and reinstall, tried to add `private: true` to all `package.json` files. No luck

**Comment by sanchit3008** [comment]
This seems odd, what is your node version?

**Comment by seleckis** [comment]
v18.12.1

**Comment by sanchit3008** [comment]
Thanks, I will check with this setting and let you know. I have been using it on 16.15.1 with yarn 1.22.19 for months now without problems.

**Comment by sanchit3008** [comment]
Sorry I am unable to reproduce this with yarn 1.22.19 / node 18.12 too. Just to be sure, you are running these commands in the root level of the repo right? This error would occur in case of a mismatch between the lockfile and the package.json.

**Comment by seleckis** [comment]
This is fresh install to a separate folder which is not a part of another project. I'm running these commands in the root of this repository. Just tried again: 
```
rm -rf node_modules yarn.lock
yarn
yarn dev
```
same result:
```
yarn run v1.22.19
$ npx yarn storybook
Internal Error: fortune-sheet@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
```

**Comment by sanchit3008** [comment]
i am quite clueless about this at this stage to be honest, since i am unable to replicate this or be able to understand why this is happening and nobody else has been reporting this either. lets keep this issue open for now. apologies.

**Comment by sanchit3008** [comment]
unable to reproduce this
