### ISSUE TITLE
Cells paste operation destroys data verification objects like checkbox or dropdown list

### ISSUE THREAD

**Issue by apropontas** [ruilisi/fortune-sheet#515]
**Describe the bug**
Create a data verification object e.g. checkbox. Copy any random cell and paste it in a random location on the spreadsheet. The paste operation destroys this checkbox (actually any data verification object also a dropdown list). 

When I dump the json of the data I see that dataVerification tag is set to null after the paste operation: "dataVerification":null

**To Reproduce**
1. Go to Basic Demo https://ruilisi.github.io/fortune-sheet-demo/?path=/story/features--basic
2. Click on data verification button in the button toolbar.
3. create a checkbox.
4. copy any cell
5. paste it anywhere
6. the checkbox object disappears

**Expected behavior**
Expect the checkbox to stay on the spreadsheet and retain its functionality.

https://github.com/ruilisi/fortune-sheet/assets/26191343/3214523b-8f78-4ef3-9c93-8682b0506632

**Comment by sanchit3008** [comment]
Thanks for submitting this, I am having a look into this.

**Comment by sanchit3008** [comment]
raised #529 @apropontas
