### ISSUE TITLE
A formula is not recalculated if depends on a dropdown list or checkbox

### ISSUE THREAD

**Issue by apropontas** [ruilisi/fortune-sheet#516]
**Describe the bug**
A formula that depends on a dropdown list or checkbox is not recalculated if user chooses another value.

**To Reproduce**
1. Go to Basic Features Demo https://ruilisi.github.io/fortune-sheet-demo/?path=/story/features--basic
2. create a drop down list with 2 values: 1 and 2 in E1
3. choose value 1
4. In the next cell create a formula and point to the cell with the dropdown list =E1
5. It will show the value 1
6. change the value in dropdown list to 2
7. the value of the formula stays 1

**Expected behavior**
A formula is recalculated when user chooses another option in a data verification object like dropdown list

https://github.com/ruilisi/fortune-sheet/assets/26191343/e648c47a-8dce-4918-b332-bb8983322d41

**Comment by sanchit3008** [comment]
thanks for submitting, i will look into this
