### ISSUE TITLE
Release frequency and rights

### ISSUE THREAD

**Issue by sanchit3008** [ruilisi/fortune-sheet#521]
Can we please have a wiki detailing the steps to be followed for releasing a new version? Also, is it possible for me to have this permission? It will help the community not wait for too long to use any newly merged fixes.  Thanks a lot for your hardwork.

@zyc9012 @gazedreamily

**Comment by sanchit3008** [comment]
@zyc9012

**Comment by zyc9012** [comment]
I'm going to build it into CI

**Comment by sanchit3008** [comment]
thanks @zyc9012 . can we please take this up on priority? i feel a lot of people who want to use the library are apprehensive because of absence of a release schedule.

**Comment by sanchit3008** [comment]
also, would it be possible for you to release a version now ? i really need a few changes which were merged.

**Comment by zyc9012** [comment]
@Qaplagzy

**Comment by Qaplagzy** [comment]
Released 0.19.3☕️

> also, would it be possible for you to release a version now ? i really need a few changes which were merged.

**Comment by sanchit3008** [comment]
thank you so much @Qaplagzy

**Comment by zyc9012** [comment]
@sanchit3008 @Qaplagzy Now when you create a new release in this repo, it will trigger Github Actions and publish the npm package.

**Comment by sanchit3008** [comment]
@zyc9012 can you please elaborate how to create a new release? Does this just mean merging code to master, or does it mean creating one of these pull request and merging it - https://github.com/ruilisi/fortune-sheet/pull/526

Thanks a lot for your hardwork with fortunesheet

**Comment by zyc9012** [comment]
@sanchit3008

* First push a new tag.

```
git tag v0.9.14`
git push --tags
```

* Go to the [release page](https://github.com/ruilisi/fortune-sheet/releases)
* Click "Draft a new release"
* Select the tag you just created
* Click "Generate release notes"
* Click "Publish release"

**Comment by sanchit3008** [comment]
thanks, i have added the steps to the wiki

https://github.com/ruilisi/fortune-sheet/wiki/Releasing-new-versions
