### ISSUE TITLE
Inserting a column to the right will bring dataVerification in the front column to the inserted column

### ISSUE THREAD

**Issue by dxxx032** [ruilisi/fortune-sheet#523]
Inserting a column to the right will bring dataVerification in the front column to the inserted column

**Comment by sanchit3008** [comment]
hi @dxxx032 , thanks for submitting this issue. can you please post a screen recording of this?

**Comment by Corbe30** [comment]
@dxxx032 It seems intentional, Google sheets behaves the same.
