### ISSUE TITLE
Not being able to change font family of cell having multiple lines.

### ISSUE THREAD

**Issue by himanshupatil363** [ruilisi/fortune-sheet#524]
When we are trying to write mutli-line text in any of the cells it gets formatted in Arial font by itself and we can't change it to any other font after that. Could you please provide a help in this?

**Comment by sanchit3008** [comment]
hi, can you please share a screen recording of this?

**Comment by himanshupatil363** [comment]
https://github.com/ruilisi/fortune-sheet/assets/60534916/39e0680c-5c43-4a99-a557-7715ff4a8c90

**Comment by sanchit3008** [comment]
thanks, looking into this

**Comment by himanshupatil363** [comment]
Thank you so much @sanchit3008
