### ISSUE TITLE
Err : Index is not in the allowed range.

### ISSUE THREAD

**Issue by himanshupatil363** [ruilisi/fortune-sheet#525]
When trying to change font size of selected text. I am getting this error specifically for safari browser. Hereby sharing screenshot of the same.Please provide some inputs for fixing this.

![PXL_20240403_105149759~3.jpg](https://github.com/ruilisi/fortune-sheet/assets/60534916/b3b8f4e6-88ac-4090-9143-7ef076fd8e82)

**Comment by sanchit3008** [comment]
hi, can you please post a screen recording of the error being reproduced? will help debugging. thanks.

**Comment by himanshupatil363** [comment]
There are two issues actually:
note : This issue is for safari browser specifically

1) Inability to apply font size to specific text: When I select the entire cell, I am able to change the font size. However, when I try to select specific text within the cell and adjust the font size, the selection disappears and the font size change is not applied.
2) Error: Occasionally, when attempting the aforementioned action, an error occurs. I have attached a screenshot of the error in the issue. Although the error does not consistently replicate in Storybook, it consistently occurs in our application.

**Comment by himanshupatil363** [comment]
https://github.com/ruilisi/fortune-sheet/assets/60534916/f701bb0b-89b4-4bdc-984f-e4a6d32108f9

**Comment by sanchit3008** [comment]
thanks, @himanshupatil363 . im not entirely sure at this point whats causing this but let me have a look.

**Comment by sanchit3008** [comment]
i looked into this, and i am unable to replicate the error in the storybook after multiple tries. however, the inability to apply font size is something i have confirmed and working on.

**Comment by himanshupatil363** [comment]
Thanks also do we have any option to use custom font family in fortunesheet?

**Comment by sanchit3008** [comment]
havent seen it being done yet, i might be wrong since i recently started contributing. 

also, i can now confirm that the error you are storybook is reproducible now for me and i will fix that. but not being able to change the font is something which is looking tricky as safari and chrome are fundamentally different when it comes to selecting text.

**Comment by sanchit3008** [comment]
@himanshupatil363 i have raised #528 which will ensure that the sheet does not break, but safari handles selection differently than chrome, which is why the selection gets lost on clicking the menus. this will require a deeper dive.
