### ISSUE TITLE
Implementing SF Hello Font for Entire Report

### ISSUE THREAD

**Issue by himanshupatil363** [ruilisi/fortune-sheet#531]
We aim to apply the SF Hello font throughout our report. Is there any built-in way we can do this? If not what is the best possible solution/approach to achieve this. (Note: We are looking for solution which will work flawless on safari primarily)

**Comment by sanchit3008** [comment]
currently, there is no way to achieve this. one way suggested by @Akxe was to use the local fonts access api. we are willing to integrate that if the community can contribute.

**Comment by Akxe** [comment]
I think that there should be options: 

- basic fonts
- Font files (drag and drop)
- if available, [the local font API](https://developer.mozilla.org/en-US/docs/Web/API/Local_Font_Access_API)

**Comment by himanshupatil363** [comment]
Hi @sanchit3008 Thanks for the revert back. would love to discuss on this further. Could you please drop your mail-Id?

**Comment by sanchit3008** [comment]
im not the sole or the main maintainer for this project, so taking this up with me will not be the best choice sorry.

**Comment by himanshupatil363** [comment]
Yes @sanchit3008 we understand we just had some doubt it would be really helpful if we can get in touch also could you share who is the main maintainer of the project?
