### ISSUE TITLE
Config cellReadOnly

### ISSUE THREAD

**Issue by pmc-quynang** [ruilisi/fortune-sheet#533]
**Is your feature request related to a problem? Please describe.**
Are there any feature that can disabled cell input?
**Describe the solution you'd like**
I think we can have this config
"cellReadOnly": [[1, 2], [3,4]......[col_index, row_index]]

**Comment by sanchit3008** [comment]
pls check the `lo` property on individual cell level

https://github.com/ruilisi/fortune-sheet/blob/master/stories/data/protected.ts
