### ISSUE TITLE
Arrows don't work as expected in Firefox/Archlinux

### ISSUE THREAD

**Issue by pezr** [ruilisi/fortune-sheet#537]
Arrows UP/DOWN/LEFT/RIGHT, don't Move cell selection box. Instead, they change cell to edit mode.

Browser: Firefox 124.0.1
OS: Archlinux, Gnome (45 & 46)

In Chromium works as expected.

Cheers.

**Comment by sanchit3008** [comment]
hi, thanks for reporting this. i dont have a copy of arch with me to test this, will check if this is the same on firefox on windows/mac. would it be possible for you to attach a screenrecording from https://ruilisi.github.io/fortune-sheet-demo/?path=/story/features--basic showing this behaviour?

**Comment by pezr** [comment]
upgraded to 19.4 and works correctly
