### ISSUE TITLE
Workbook not displaying in dynamic route next js 14

### ISSUE THREAD

**Issue by fazzyA** [ruilisi/fortune-sheet#538]
**Describe the bug**
I have next js 14 where i have route of localhost:3000/workroom/[id]. I am using ap router in next js.
When I call `<Workbook {...settings} />`
It does not load properly. sheet space is there but no sheet is being displayed. 

**To Reproduce**
1. Run next js app by `npm run dev`
2. create route in app folder by making workroom folder then [id] folder and make page.tsx
3.  Render the workbook
<Workbook {...settings} />
4. const settings = {
     data: [{ name: 'Sheet1', celldata: [{ r: 0, c: 0, v: null }] }], // sheet data
     onChange: (data) => {}, // onChange event
     lang:'zh' // set language
     // More other settings...
}

**Expected behavior**
A clear display of workbook
![image](https://github.com/ruilisi/fortune-sheet/assets/7613167/070025df-bf0e-44f0-a6d7-0fe75ca00835)

**Screenshots**
![image](https://github.com/ruilisi/fortune-sheet/assets/7613167/55ea99fc-d9f5-46f4-abe5-0f20639664bd)

**Comment by sanchit3008** [comment]
hi, can you please check thew console if there is any error logged? i dont have a next js setup handy to check this.

**Comment by fazzyA** [comment]
ok so i called workbook like belo and noe its working.
                    <Workbook
                      ref={ref}
                      column={5}
                      row={5}
                      allowEdit
                      addRows={1}
                      defaultColWidth={170}
                      defaultRowHeight={32}
                      rowHeaderWidth={54}
                      columnHeaderHeight={0}
                      data={data}
                      onChange={onChange}
                    />

**Comment by sanchit3008** [comment]
thanks, closing this
