### ISSUE TITLE
Do you have any plans to provide a method for parsing Excel files? This feature has a wide range of requirements

### ISSUE THREAD

**Issue by alindas** [ruilisi/fortune-sheet#542]
I am unable to obtain information related to this from the official website. Does it already exist or have I overlooked it

**Comment by sanchit3008** [comment]
by parsing excel files, do you imply importing data from excel to fortunesheet?

**Comment by alonesmall** [comment]
> by parsing excel files, do you imply importing data from excel to fortunesheet?

yes

**Comment by sanchit3008** [comment]
hi, this feature does not exist yet. i think as an intermediate solution, a custom data processor can be used to convert data from the format provided by the xlsx package to what fortunesheet expects.
