### ISSUE TITLE
yarn build failing after formula parser upgrade

### ISSUE THREAD

**Issue by sanchit3008** [ruilisi/fortune-sheet#544]
@zyc9012 `yarn build` is failing after #532 

https://github.com/ruilisi/fortune-sheet/actions/runs/8967287069

It fails with an import error, while in reality the  imported property is being exported. Could you have a look pls? I am also trying to figure out. Also, should release.yml build formula parser first, then core, and then react?

**Comment by zyc9012** [comment]
@sanchit3008 Pushed a fix.

However, I member the following part was manually inserted.

`git diff 0bc2c6c..HEAD grammar-parser.js`

```diff
@@ -755,11 +672,6 @@ next:function () {
             if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                 match = tempMatch;
                 index = i;
-                const stackLen = stackCache.length
-                if (rules[i] === 8 && match[0].match(NUMONLY) && !(match.input.slice(match[0].length)[0] === ":" || (stackLen > 3 && stackCache[stackLen - 4] === 25 && stackCache[stackLen - 2] === 27))) {
-                  match = false;
-                  continue;
-                }
                 if (this.options.backtrack_lexer) {
                     token = this.test_match(tempMatch, rules[i]);
                     if (token !== false) {
```

Please double-check if removing this part breaks anything.

**Comment by sanchit3008** [comment]
is `yarn build` running for you after this fix? im still getting the same issue.

**Comment by zyc9012** [comment]
@sanchit3008 You have to `yarn` first to build the `formula-parser`

**Comment by sanchit3008** [comment]
ah that was stupid of me...it builds on my local machine now. hopefully the release action will run fully now.

**Comment by zyc9012** [comment]
I think you need to re-tag v0.19.6

**Comment by sanchit3008** [comment]
on it

**Comment by sanchit3008** [comment]
finally it succeeded, thanks for all the help, you are too kind
