### ISSUE TITLE
Pasting value like 01 from excel to fortune sheet becomes 1 and format is reset to number if set to text on initialization

### ISSUE THREAD

**Issue by Mussawerx** [ruilisi/fortune-sheet#547]
**Describe the bug**
Pasting value like 01 or '01 from excel to fortune sheet becomes 1 and format is reset to number if set to text on initialization

**To Reproduce**
1. Create a sheet like this:
![image](https://github.com/ruilisi/fortune-sheet/assets/147578780/c34c2895-ab37-4c7e-968f-282b1e6de3f8)

2. Copy the contents within the range
3. Paste them to Forune Sheet:
![image](https://github.com/ruilisi/fortune-sheet/assets/147578780/9e95453f-4ceb-4b5f-b1e4-7c95a32bc1c0)
5. See error

**Expected behavior**
When pasting the format should remain the same even if I am trying to set the cell format on initialization to text on pasting the format is reset to general and cell type to number which causes the error of 01 becoming 1 while pasting. The paste should not touch the original format at least.

**Screenshots**
I have pasted the screenshots above for better understanding

**Additional context**
Kindly fix it urgently as its a major requirement and hurdle in our development

**Comment by shaiqxemustafa** [comment]
+1

**Comment by Mussawerx** [comment]
In the behavior show cased in video it should behave the way it is being depicted, but if apostrophe( ' ) is used before number like this -'01 it must keep the format when pasting in the sheet and should keep the format while pasting
