### ISSUE TITLE
Need to convert Sheet data to excel

### ISSUE THREAD

**Issue by fazzyA** [ruilisi/fortune-sheet#550]
I want to convert my fortune workbook data into excel file. is there anyway I can do it or save it in format like pandas dataframe. so use it for later. I need to save sheet(s) data to google storage but can not keep this much long complex data. If I can convert it to some type and store. Also need to convert data back, so it can be displayed back into the plugin.

**Comment by sanchit3008** [comment]
I believe you can write your own function to convert the data into csv and then import that into excel (though styling would be lost that way). Then you can just write the inverse of that function too to import it back into FS. Excel export-import is something we want to do but not sure when that will happen.
