### ISSUE TITLE
TODAY() function is not working

### ISSUE THREAD

**Issue by subhajitnag28** [ruilisi/fortune-sheet#551]
TODAY() function is not working, it is giving NaN.

<img width="1431" alt="Screenshot 2024-05-29 at 5 36 55 PM" src="https://github.com/ruilisi/fortune-sheet/assets/35533400/8a09fb04-ded3-480f-9407-a48f4626c04e">

<img width="1435" alt="Screenshot 2024-05-29 at 5 37 12 PM" src="https://github.com/ruilisi/fortune-sheet/assets/35533400/f5c783e0-6a94-4e9a-8351-ef6866d8d29b">

**Comment by sanchit3008** [comment]
I see that the `TODAY()` function from formulajs returns a date object, but the sheet can support only string and number. Would setting the cell value as string like `Sat Jun 01 2024 00:00:00 GMT+0530 (India Standard Time)` work for you?

**Comment by sanchit3008** [comment]
Following function have the same issue - 

- WORKDAY
- DATE
- DATEVALUE
- TODAY
- EDATE
- EOMONTH
- NOW
- WORKDAYINTL

**Comment by sanchit3008** [comment]
@zyc9012 what are your thoughts on this? I was thinking to have a check in `execfunction` in `formula.ts` to see if the result of the formula parser is a date, and to return `result.toString()` if it is a date.

**Comment by subhajitnag28** [comment]
Hi @sanchit3008 I think it should work. Can you please help to make the change?

**Comment by sanchit3008** [comment]
I have the changes ready, will wait for @zyc9012's inputs for a couple of days

**Comment by subhajitnag28** [comment]
Thanks @sanchit3008

**Comment by sanchit3008** [comment]
#553
