### ISSUE TITLE
Right click on sheet throw application error

### ISSUE THREAD

**Issue by faizaGS** [ruilisi/fortune-sheet#554]
I have integrated fortune sheet in next js project.
Node: v21.6.1, Next js: 14.1.0
When i load the work book and display on the browser by running the project, it runs fine.
But whn i right click on any of the cells, it throws application error. After refresh, the page is working again.
Some screenshots are given.
In below image the workbook is rendering fine.
![image](https://github.com/ruilisi/fortune-sheet/assets/92626888/e5658a5a-a698-40bf-9045-8080d8853636)
now after right click of any cell gives this error
![image](https://github.com/ruilisi/fortune-sheet/assets/92626888/deff0491-147b-4081-8afd-1609c61d5c31)

**Comment by sanchit3008** [comment]
will try to reproduce this, thanks.

**Comment by sanchit3008** [comment]
I doubt that this is a fortune sheet issue. Could you please try suggestions from quick google searches on regeneratorRuntime not defined error?

**Comment by sanchit3008** [comment]
Will be picking this up

**Comment by sanchit3008** [comment]
please upgrade to 0.19.10 and check once

**Comment by october-rain** [comment]
> please upgrade to 0.19.10 and check once
sorry, i still have this problem. pls check this demo [codesandbox](https://codesandbox.io/p/sandbox/fortune-sheet-4pp3q6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzjillix00063b6ljerpop28%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzjillix00023b6l2l081h80%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzjillix00033b6l3jm9k48t%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzjillix00053b6lbqmwbinr%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzjillix00023b6l2l081h80%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzjilliw00013b6lq4l40wnd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzju3a7a00023b6l1dzwz6qj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A43%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A43%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzjillix00023b6l2l081h80%2522%252C%2522activeTabId%2522%253A%2522clzju3a7a00023b6l1dzwz6qj%2522%257D%252C%2522clzjillix00053b6lbqmwbinr%2522%253A%257B%2522id%2522%253A%2522clzjillix00053b6lbqmwbinr%2522%252C%2522activeTabId%2522%253A%2522clzjipl6u001q3b6l5zu7cags%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzjillix00043b6lug2xmxzo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clzjipl6u001q3b6l5zu7cags%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzjillix00033b6l3jm9k48t%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzjillix00033b6l3jm9k48t%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by october-rain** [comment]
> please upgrade to 0.19.10 and check once

sorry, i still have this problem in 0.19.12, plz check this demo [codesandbox](https://codesandbox.io/p/sandbox/fortune-sheet-4pp3q6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzjillix00063b6ljerpop28%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzjillix00023b6l2l081h80%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzjillix00033b6l3jm9k48t%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzjillix00053b6lbqmwbinr%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzjillix00023b6l2l081h80%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzjilliw00013b6lq4l40wnd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzju3a7a00023b6l1dzwz6qj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A43%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A43%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzjillix00023b6l2l081h80%2522%252C%2522activeTabId%2522%253A%2522clzju3a7a00023b6l1dzwz6qj%2522%257D%252C%2522clzjillix00053b6lbqmwbinr%2522%253A%257B%2522id%2522%253A%2522clzjillix00053b6lbqmwbinr%2522%252C%2522activeTabId%2522%253A%2522clzjipl6u001q3b6l5zu7cags%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzjillix00043b6lug2xmxzo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clzjipl6u001q3b6l5zu7cags%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzjillix00033b6l3jm9k48t%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzjillix00033b6l3jm9k48t%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

![image](https://github.com/user-attachments/assets/fad40b28-ddba-48fa-b973-a97f6df6ed2c)

**Comment by sanchit3008** [comment]
geez this is unexpected, reopening this issue.
