### ISSUE TITLE
How to get height and width dynamically after resize the row and column and copy - paste

### ISSUE THREAD

**Issue by subhajitnag28** [ruilisi/fortune-sheet#555]
Hi @sanchit3008 can you please guide me how to get the height and width dynamically after resize the row and column? In my scenario user can add multiple fortunesheet and based on the height and width I need to display the preview. I tried based on the config rowlen and columnlen dynamic height and width calculation but the last row is not coming properly. After I adjust the height of last row it display. But with different multiple template it causes an issue, the last content is not visible. Can you plesae guide   me.

**Comment by sanchit3008** [comment]
Hello, I am not sure if I understood your question correctly.

**Comment by subhajitnag28** [comment]
Hi, I'm able to fix it. You please close the ticket.
