### ISSUE TITLE
How to know which fortunesheet is currently focused 

### ISSUE THREAD

**Issue by subhajitnag28** [ruilisi/fortune-sheet#556]
Hi @sanchit3008 can you please guide how to know which fortunesheet is currently focused if single or multiple fortunesheet we added and whichever fortunesheet we edited my focus should be updated to that fortuneshhet only ? and If we click outside of the fortunesheet how to removed the selection where my last cursor point was?

**Comment by sanchit3008** [comment]
This is a good question, and I dont see a method to return the currently active sheet. I still need to play around a bit to see if this info is being returned by something else. Keeping this thread open.

For the second part, you can probably attach a click listener outside FS and then use the setSelection method

**Comment by subhajitnag28** [comment]
Hi @sanchit3008 If we click outside of the fortunesheet how to removed the selection where my last cursor point was? 

I attach a click listener outside FS and then use the setSelection method but I'm getting the below error - 
![WhatsApp Image 2024-06-12 at 19 28 41](https://github.com/ruilisi/fortune-sheet/assets/35533400/cd4fade9-d321-44b6-a8e1-f04431b0ee86)

when there is one FS there is no issue with the error but if we are creating multiple FS, in the second FS onward I'm not able to update anything.

Can you please guide me.

**Comment by sanchit3008** [comment]
If I understand this correctly, you want to have multiple sheets on a page. When you click outside the sheet area you want the selection to be removed. 

1. Are you using multiple `Workbook` components or are you referring to multiple sheets in 1 workbook?
2. When the user click the sheet component again, then what is the expectation?

**Comment by Corbe30** [comment]
Hi @subhajitnag28! To remove the selection, use this. It will not show the `rf and cf is nil` error in console.
```
ref.current?.setSelection(undefined);
```
