### ISSUE TITLE
='Sheet1'!A1 generates error

### ISSUE THREAD

**Issue by ojrestrepom** [ruilisi/fortune-sheet#557]
**Describe the bug**
![image](https://github.com/ruilisi/fortune-sheet/assets/70527838/9d8085b4-2539-4810-b7e9-59d257436258)

When I use the demo I can reference cells in other sheets. But when I use it in an application it generates an error.
![image](https://github.com/ruilisi/fortune-sheet/assets/70527838/41301c01-d4f9-4e54-9366-5835e4948f9c)
And it doesn't matter if I use single quotes or not. Error is generated.

The cell reference appears in the calcChain. But he doesn't recognize the formula when I enter the name of the sheet.
Could you tell me what to do? I am working on the development in Next JS 14
Thank you

**Comment by sanchit3008** [comment]
Thanks for reporting this. Will try reproducing this.

**Comment by sanchit3008** [comment]
I was able to reproduce this, working on a fix.

**Comment by sanchit3008** [comment]
@zyc9012 i just noticed that this feature is not working even if you revert to commits that are 6 months old. Any clue what could be going on?

**Comment by sanchit3008** [comment]
https://github.com/ruilisi/fortune-sheet/commit/906216e7a9ee0c5161057d6709a4892de20ad8e2?diff=unified&w=1

while updating the grammar parser, the lines for checking the sheet names were removed.
