### ISSUE TITLE
无法安装了

### ISSUE THREAD

**Issue by cy2zq** [ruilisi/fortune-sheet#561]
**Describe the bug**
Install fail! Error:npm 镜像我都试了，下午还好的
<img width="1375" alt="image" src="https://github.com/ruilisi/fortune-sheet/assets/40606690/e4e7cd04-cdb7-43ab-8759-d2ad02d07057">

**Comment by sanchit3008** [comment]
hello, this seems like a mistake since the version `0.2.12` is available on npm.js

can you please clear your npm cache and try?

https://www.npmjs.com/package/@fortune-sheet/formula-parser/v/0.2.12
