### ISSUE TITLE
setDataVerification(option, [setting])

### ISSUE THREAD

**Issue by ojrestrepom** [ruilisi/fortune-sheet#565]
setDataVerification appears in the Luckysheet API. Is there something in the FortuneSheet API that allows you to create a dataVerification?
![imagen_2024-07-01_113155694](https://github.com/ruilisi/fortune-sheet/assets/70527838/c91aacc4-737a-4410-afce-ec7f203fa293)

**Comment by sanchit3008** [comment]
hi, thanks for the question. i dont see an API to set data verification like this in the codebase.
