### ISSUE TITLE
Further language support 

### ISSUE THREAD

**Issue by bgareth** [ruilisi/fortune-sheet#567]
My team is wanting to make use of this library, however we are obligated to have translation support for many languages for all of our content. We currently support 17 languages and intend to reach 30 within a year or so. 

The languages that we currently support and need supported here:
- English (en) ✅
- Arabic (ar)
- Simplified Chinese (zh) ✅
- Dutch (nl)
- French (fr)
- German (de)
- Italian (it)
- Japanese (ja)
- Korean (ko)
- Portuguese (pt)
- Spanish (es)
- Turkish (tr)
- Polish (pl)
- Zulu (zu)
- Ukrainian (uk)
- Vietnamese (vi)
- Azerbaijani (az)

All of the languages mentioned above need to be supported. We are willing to facilitate the translations and contribute to the repo. We work with professional translators, using CrowdIn, to translate.

We have not kicked off this work and therefore have not made a 100% commitment to completion yet. In the meantime, if anyone can share any details and additional considerations, that would be much appreciated.
As understood, the only requirement needed is to create and 100% translate the locale specific files along with updating the `index.ts` file in `fortune-sheet/packages/core/src/locale`.

**Comment by sanchit3008** [comment]
hi, thanks a lot for reaching out. if i understand correctly, you are willing to translate the strings and just need to confirm the things you need to change, right?

**Comment by bgareth** [comment]
Thanks for the response, @sanchit3008.
Essentially, yes. We are likely to commit to the work, so I was putting a feeler out in case there was any missed or misunderstood requirements.

**Comment by sanchit3008** [comment]
Apart from the locale files, I can see that the following translations will also need to be made - 

1. `core/src/context.ts` has some option labels in the supported languages
2. `core/src/modules/dataVerification.ts` has some failure texts and hint values 
3. new locale files will need to be added to the locale folder, and corresponding entries be made to the `localeObj` in `locale/index.ts`

**Comment by bgareth** [comment]
@sanchit3008 thank you vey much. I will update the issue once we have kicked off and have estimations. 
We're considering submitting a couple other issues and PRs soon, hopefully up to scratch to improve an already great open source.

**Comment by sanchit3008** [comment]
sounds great! thanks for doing this.

**Comment by sanchit3008** [comment]
fyi @zyc9012

**Comment by sanchit3008** [comment]
@bgareth https://github.com/ruilisi/fortune-sheet/wiki/Adding-support-for-new-languages

**Comment by sanchit3008** [comment]
I am closing this issue now @bgareth , will review any future PRs you raise for any of these langs
