### ISSUE TITLE
Improve keyboard and screen-reader related accessibility

### ISSUE THREAD

**Issue by bgareth** [ruilisi/fortune-sheet#573]
My team is wanting to make use of this library, however we noted some accessibility improvements needed from our end. 
- Toolbar
  - `aria-label` on toolbar button (can use the same text as the button tooltip)
  - Toolbar button images are decorative and require `alt-text=""`
  - Add `aria-label="Toolbar"` to large toolbar group for section context (add "Toolbar" string and translations)
- Cell keyboard navigation
  - Add support for `Shit + Tab` to move cell focus left
- Add tab indices to all tags with an `onClick` attribute

While some of these are required to pass certain accessibility standards ([WCAG 2.1](https://www.w3.org/TR/WCAG21/)), others improve the keyboard navigation and screen reader experience.

A [PR](https://github.com/ruilisi/fortune-sheet/pull/574) has already been created from [this fork](https://github.com/labxchange/fortune-sheet).
(`npx prettier --write ./packages` was needed to push commits for the large scope of the tab indices update)

**Comment by sanchit3008** [comment]
Hi, thanks for pointing these out! I'll start reviewing if you're willing to raise a pr to this project?

**Comment by bgareth** [comment]
Thank you so much @sanchit3008. I have edited the issue to point to the [PR](https://github.com/ruilisi/fortune-sheet/pull/574) for transparency. 
Please let me know if there are any questions or concerns as one does in PRs, really appreciate your collaboration.

**Comment by sanchit3008** [comment]
sure thing. its going to take me some time to review this though.

**Comment by sanchit3008** [comment]
have closed this issue
