### ISSUE TITLE
表格中的数据有换行会非常卡

### ISSUE THREAD

**Issue by isdefault** [ruilisi/fortune-sheet#578]
例如表格中的数据如下：
1.测试文本
1.测试文本
1.测试文本
1.测试文本
这只是简单的示例，如果换行较多或者文本比示例的长会非常卡，即使只使用上面的示例文本也会卡，如果没有换行就不会卡例如
1.测试文本1.测试文本1.测试文本1.测试文本

**Comment by isdefault** [comment]
![1](https://github.com/user-attachments/assets/ba0f0494-b31d-4a7a-8029-4debcef9c086)

**Comment by isdefault** [comment]
单个单元格数据多的话会非常卡

**Comment by sanchit3008** [comment]
hi can you please post this in english? sorry i cant understand chinese.

**Comment by isdefault** [comment]
> 嗨，你能用英文发布这个吗？对不起，我听不懂中文。

It can be very stuck when there are a lot of characters in a single cell in the table, you can take a look at the performance graph of the screenshot I commented on above

**Comment by isdefault** [comment]
> 嗨，你能用英文发布这个吗？对不起，我听不懂中文。It can be very stuck when there are a lot of characters in a single cell in the table, you can take a look at the performance graph of the screenshot I commented on above

**Comment by sanchit3008** [comment]
i will have a look at this. thanks for reporting.

**Comment by Corbe30** [comment]
Hi @isdefault ! Which browser, browser version and OS are you using?
This issue is caused by canvas' `filltext()`, which is particularly slow on Linux implementation of Chrome and Firefox.

That said, I've raised a fix [PR](https://github.com/ruilisi/fortune-sheet/pull/615) ✨

**Comment by isdefault** [comment]
Thank you for taking the time to fix this

**Comment by isdefault** [comment]
I'm using chrome and Edge
