### ISSUE TITLE
单元格处于编辑状态时，右键菜单插入行列代码报错，页面白屏

### ISSUE THREAD

**Issue by huihuzhao** [ruilisi/fortune-sheet#580]
![75bbc2f9a7ef2c18a304e314f4e20ac](https://github.com/user-attachments/assets/b24b32ad-2b6a-4fa2-9457-945d5529e088)

![3d3603375db6e2b9b690fdb10a73724](https://github.com/user-attachments/assets/0842e396-643a-4166-81d5-634988fa5447)

**Comment by sanchit3008** [comment]
Hi, can you please post this in English? I don't know Chinese. I will have a look.

**Comment by huihuzhao** [comment]
> Hi, can you please post this in English? I don't know Chinese. I will have a look.

When the cell is in the editing state, use the right-click menu to insert a row or column, the code reports an error, and the page is white.  Thank you.

**Comment by huihuzhao** [comment]
> Hi, can you please post this in English? I don't know Chinese. I will have a look.

![9b122b55780d16200f0ee1d5b1fbb8f](https://github.com/user-attachments/assets/3086ed44-6f1f-4c70-ab5a-8f2bb27652d8)

**Comment by sanchit3008** [comment]
Thanks, I will have a look this week

**Comment by sanchit3008** [comment]
I had a look at this. Usually softwares like google sheets don't even allow such actions when the cell is being edits, but that its a very big change to do for us. I will add a few checks so it does not break when somebody inserts row/col while editing, but that is unexpected behaviour tbh.
