### ISSUE TITLE
"Paste" option broken

### ISSUE THREAD

**Issue by bgareth** [ruilisi/fortune-sheet#584]
**Describe the bug**
Clicking "Paste" no longer works.
There is an error in the console:
```
TypeError: Cannot read properties of undefined (reading 'readText')
```

**To Reproduce**
1. Copy cell(s)
2. Right click on cell(s)
3. Select "Paste"

**Expected behavior**
The copied cell(s) content should be pasting / placed in the selected cell(s) when "Paste" is selected.

**Screenshots**
<img width="430" alt="Screenshot 2024-08-09 at 9 01 49 AM" src="https://github.com/user-attachments/assets/283c9be4-442e-4167-9136-01cb9f824481">

**Additional context**
This error seems to have been introduced recently. I updated the library within my environment a couple weeks ago and it was working. I updated the library within my environment yesterday and it was broken. I see there have been some mergers in that time.

**Comment by sanchit3008** [comment]
hi, thanks for reporting this. i am looking into this.

**Comment by sanchit3008** [comment]
which browser and version are you on @bgareth

**Comment by bgareth** [comment]
> which browser and version are you on @bgareth ? also, is the webpage http or https?
@sanchit3008 

Testing was done on Chrome Version 127.0.6533.100 on both http and https.

**Comment by sanchit3008** [comment]
It'll not working on http, but should work on https with chrome. That's odd. Can you create a sandbox for this ?

**Comment by bgareth** [comment]
Hi @sanchit3008, tests are being done within our environment, I'll update here. Thank you for the help.

**Comment by sanchit3008** [comment]
No problem. I'm quite surprised that this is happening though. Any modern browser that supports navigator.clipboard shouldn't be having these issues.

**Comment by bgareth** [comment]
> No problem. I'm quite surprised that this is happening though. Any modern browser that supports navigator.clipboard shouldn't be having these issues.

It may be something in our environment. If you like, we can close the issue and after further testing on our side I can always create a new one.

**Comment by sanchit3008** [comment]
No issues, you can keep this open until it works for you. Since this is serious enough, we can probably connect over this as well.

**Comment by bgareth** [comment]
@sanchit3008 I apologies for the unnecessary issue, further testing revealed an environment issue on our end. 
I am closing the issue.

**Comment by bgareth** [comment]
@sanchit3008 I apologies for the unnecessary issue, further testing revealed an environment issue on our end.
I am closing the issue.

**Comment by sanchit3008** [comment]
Thanks, what exactly was the issue though
