### ISSUE TITLE
bug提交, 窗口变化, 会影响选取. 附有gif动画

### ISSUE THREAD

**Issue by 888go** [ruilisi/fortune-sheet#588]
窗口尺寸变化, 会影响到选区
![3](https://github.com/user-attachments/assets/2b526d32-3f5b-44ac-9776-40e82e8cb35f)

**Comment by sanchit3008** [comment]
thanks for reporting this, will have a look at this

**Comment by Corbe30** [comment]
@888go which browser are you using? I observe it after 'fullscreen' event in safari and chrome, but not on resizing events.
