### ISSUE TITLE
Suggestion: auditing mechanism for changes

### ISSUE THREAD

**Issue by jmptrader** [ruilisi/fortune-sheet#6]
Hi,

It would be nice to consider including an auditing mechanism for changes (actions and data) that are performed in a spreadsheet.

I have seen an interesting idea in the Ethercalc project [https://github.com/audreyt/ethercalc]

Each change is transformed into instructions, for example:

set A1 text t Hi, Friends.
set A2 value n 15
set A3 value n 20
set A4 formula sum(A2:A3)
set A4 font normal bold * *
cut A2:A4 formulas
paste B2 formulas

Others applications, you can persist this and replay changes. It would be a very interesting function with many possibilities, don't you think?

**Comment by zyc9012** [comment]
Do you mean recording user operations? If so, we have `Op` that is emitted on each user operation. These `Op`s  are used for persistence and undo/redos.

See https://github.com/ruilisi/fortune-sheet#backend-storage-and-collabration for brief, or https://ruilisi.github.io/fortune-sheet-docs/guide/op.html for detaild explanation.

If you also need to convert the op into human readable string, we can put that into schedule.
