### ISSUE TITLE
beforePaste 异步返回false后仍然可以粘贴

### ISSUE THREAD

**Issue by Rio-shuai** [ruilisi/fortune-sheet#601]
目前 beforePaste 可以拦截粘贴操作了，但是不满足我的使用场景。
我需要获取剪切板中的内容，然后根据我自己的规则判断是否允许粘贴，其中获取剪切板的内容是异步操作。 我异步返回false时 仍然会将数据粘贴进去。
示例代码：
```
<Workbook
    {...config}
    hooks={{
        beforePaste: async ()=>{
            const pasteText = await navigator.clipboard.readText();
            const allowPaste = pasteText === '123';
            return allowPaste
        }
    }}
/>
```

Current beforePaste can block paste operations, but it does not meet my usage scenario.
I need to get the contents of the clipboard and then decide whether to allow pasting according to my own rules, where getting the contents of the clipboard is an asynchronous operation. Even if `false` is returned, the data will still be pasted in.
Sample  code:
```
<Workbook
    {...config}
    hooks={{
        beforePaste: async ()=>{
            const pasteText = await navigator.clipboard.readText();
            const allowPaste = pasteText === '123';
            return allowPaste
        }
    }}
/>
```

我希望组件可以兼容异步返回的场景
I want the component to be compatible with asynchronously returned scenarios

**Comment by sanchit3008** [comment]
Hey, I had a look at this request today. It is not possible to support async/await with this hook. But for your use case of deciding true/false based on contents being pasted, there is an inbuilt method to achieve this.

```
hooks={{
          beforePaste: (_, content) => {
            return content === "123";
          },
        }}
```

I believe this will serve your purpose.
