### ISSUE TITLE
Filtered rows in the middle are also being copied

### ISSUE THREAD

**Issue by chengwang8888** [ruilisi/fortune-sheet#605]
For example, if there are 4 rows of data and rows 2 and 3 are filtered out, then copying data to rows 1 and 2 results in rows 2 and 3 (which are filtered out) also getting the copied data. However, if the copy is done by dragging down from the first row, rows 2 and 3 (which are filtered out) do not get the copied data.

![20240927-101523](https://github.com/user-attachments/assets/d52a43aa-8cf9-4b49-b391-72bb8df6fe26)

**Comment by sanchit3008** [comment]
hey, thanks for reporting this. i wont be able to have a look for the next few days, but i will get back to you after verifying the same actions in google sheets.

**Comment by sanchit3008** [comment]
ok so i had a look at google sheets, the behaviour when the values are dragged down is correct but the copy/paste operation should not be pasting the values in the filtered out rows. is this your expectation aswell?

**Comment by chengwang8888** [comment]
> ok so i had a look at google sheets, the behaviour when the values are dragged down is correct but the copy/paste operation should not be pasting the values in the filtered out rows. is this your expectation aswell?

yes
