### ISSUE TITLE
Error When Using "=" in FortuneSheet Component

### ISSUE THREAD

**Issue by Marcel-Kaminski** [ruilisi/fortune-sheet#607]
### Bug Report: Error When Using "=" in FortuneSheet Component

**Description:**  
I am encountering an issue in a simple React project using the `FortuneSheet` component. When I enter the `=` character in any cell and then try to interact with another cell, an error occurs. 

**Steps to Reproduce:**

1. Create a basic React app.
2. Implement a component using the `FortuneSheet` library as shown below:

    ```jsx
    import React from 'react';
    import { Workbook } from 'fortunesheet';

    const FortuneSheetComponent = () => {
      const data = [
        {
          name: "Sheet1",
          celldata: [
            { r: 0, c: 0, v: { m: "A1", v: "A1" } },
            { r: 1, c: 1, v: { m: "B2", v: "B2" } }
          ]
        }
      ];

      return (
        <div style={{ width: "80vw", height: "60vh" }}>
          <Workbook
            data={data}
            onChange={(newData) => {
              console.log("Data changed:", newData);
            }}
          />
        </div>
      );
    };

    export default FortuneSheetComponent;
    ```

3. Render the `FortuneSheetComponent`.
4. Enter the character `=` in any cell.
5. Click on any other cell.

**Expected Behavior:**  
Entering `=` in a cell should not cause any errors, and the component should continue to function normally.

**Actual Behavior:**  
After entering `=` in a cell and then clicking on another cell, an error occurs, interrupting the normal behavior of the sheet.

**Screenshots/Links:**  
You can see the error message and stack trace in the following video:  
[Video](https://github.com/user-attachments/assets/bef8233d-cd59-4298-be39-9aa823c9bf00
)

**Additional Context:**  
- The issue occurs even with the basic setup and no additional configurations.  
- I'm using the latest version(^0.19.16) of the `FortuneSheet` library.

Let me know if there's any additional information I can provide to help debug this issue.

**Comment by sanchit3008** [comment]
hi marcel, thanks for reporting this. ill try to reproduce this and get back to you in case i need more info.

**Comment by sanchit3008** [comment]
this was caused by some recent changes, i apologise for this. i am pushing the fix and will release it asap.

**Comment by Marcel-Kaminski** [comment]
Thanks, I will test it and let you know!
