### ISSUE TITLE
Textbreak (tb) makes Sheet very laggy - Performance Issues Bug

### ISSUE THREAD

**Issue by Erivess** [ruilisi/fortune-sheet#610]
Im encountering significant performance issues when using fortunesheet to render Excel files that have around 40 or more rows and 3-4 containing a lot of text. The spreadsheet becomes quite laggy and impossible to work on. We do not use any editing operations and just use fortunesheet to "view" the excel file. 

I'm wondering if there's a way to optimize fortunesheet for better performance with larger datasets - even tho I would not consider 40 rows a "large dataset". 

Does fortunesheet support virtualization or any performance enhancements for big data sets?

Happy for any help.

**Comment by sanchit3008** [comment]
that should not be happening, i have used this package for sheets with 10k+ rows. you might want to relook at your implementation.

**Comment by Corbe30** [comment]
Hi @Erivess! Do your cells data have line breaks? If so, it may be linked to #578. 
If not, check for accidental re-renders in your implementation.

**Comment by Erivess** [comment]
@Corbe30 @sanchit3008  Yes, we already identified the issue: We defined tb=2 for every single cell and that caused the lag. After removing it from every cell and defining it as global style, the lag disappeared.

**Comment by Corbe30** [comment]
Hi @Erivess, we have fixed the performance issue with tb in the new release [v0.19.18](https://github.com/ruilisi/fortune-sheet/releases/tag/v0.19.18)! Let me know if you're still facing the issue.

**Comment by Erivess** [comment]
@sanchit3008 Can we reopen this issue, so its visible for everyone?

**Comment by sanchit3008** [comment]
reopening

cc @Corbe30

**Comment by sanchit3008** [comment]
trying to look into this @Erivess , can you please tell me what exactly is happening here? was the issue not solved as you had mentioned or did it reappear after v20?

also, can you give me a sample cell data and sequence of actions youre doing which i can plug in and check quickly?

**Comment by Erivess** [comment]
@sanchit3008 
it's happening on every version - I also upgraded to v20 (https://prnt.sc/xGUiwF_hcRZj) to test it and it reappears there. 

I have uploaded the workbookdata here in .txt files: https://drive.google.com/drive/folders/1v4xfStc8CbbHMK8PVEGfiIxruRzOlL9R?usp=drive_link

You can also copy and paste the data from the excel into your storybook demo empty sheet and assign "word wrap" to the cells. The lag also comes up in the demo when doing it: https://prnt.sc/542qQ6ckiU96

**Comment by sanchit3008** [comment]
i just tried out the data you provided and even with 20 cells being wrapped the performance goes to the drain wow. looking into this.

**Comment by sanchit3008** [comment]
i have managed to pinpoint why this is happening, thinking of a fix

**Comment by Erivess** [comment]
Looking forward to it! I feel like the performance drop is the worst with tb = 2 . It's also happening with 1 & 0, but not as bad as 2.

**Comment by sanchit3008** [comment]
yeah thats a somewhat correct observation, there is a method that is called whenever you do anything in the sheet, which provides info about the cells. the part where textbreak is handled must be having some heavy operations due to which this is happening.

**Comment by sanchit3008** [comment]
this is gonna take me some time, the current implementation doesnt have a scope for optimisation unless it is changed drastically

**Comment by sanchit3008** [comment]
though i have observed that the lag is inversely proportional to the width of the column having the textwrap, so as a short term relief you can maximise the width as much as possible for your app
