### ISSUE TITLE
Font Styling gets removed when viewing cell with /n linebreak

### ISSUE THREAD

**Issue by Erivess** [ruilisi/fortune-sheet#622]
**Describe the bug**
When I have a cell with a lot of text and a newline characters /n , the styling gets removed after opening the cell in full and then closing it again.

**To Reproduce**
Steps to reproduce the behavior - see images.
1. Have a cell with lots of text
2. View the cell in full
3. Close the cell again
4. -> Formatting removed

JSON output from the example: 
`  {
                        "r": 33,
                        "c": 2,
                        "v": {
                            "v": "There shall be a defined and documented method for determining the impact of any disruption to the organization (cloud provider, cloud consumer) that must incorporate the following:\n • Identify critical products and services\n • Identify all dependencies, including processes, applications, business partners, and third party service providers\n • Understand threats to critical products and services\n • Determine impacts resulting from planned or unplanned disruptions and how these vary over time\n • Establish the maximum tolerable period for disruption\n • Establish priorities for recovery\n • Establish recovery time objectives for resumption of critical products and services within their maximum tolerable period of disruption\n • Estimate the resources required for resumption",
                            "f": null,
                            "ct": {
                                "fa": "General",
                                "t": "g"
                            },
                            "bg": "#ffffff",
                            "bl": 0,
                            "it": 0,
                            "ff": "Calibri",
                            "fs": 11,
                            "fc": "#333333",
                            "ht": 1,
                            "vt": 1,
                            "tr": "0",
                            "tb": "2"
                        }
                    },`

**Expected behavior**
Cell should contain the data and not remove the styling
**Screenshots**
See screenshots
**Additional context**
I tried removing the special characters, but it only worked when removing the /n
![Screenshot at Nov 13 08-17-54](https://github.com/user-attachments/assets/e62bb108-3a1a-4224-b1cf-9712bbeb5c6a)
![Screenshot at Nov 13 08-18-22](https://github.com/user-attachments/assets/77dbcfbd-d58a-42db-ad08-58eadcfd3588)
![Screenshot at Nov 13 08-24-49](https://github.com/user-attachments/assets/fdeb5c84-e5ec-4eed-8abd-4979e946ffc6)

**Comment by sanchit3008** [comment]
https://github.com/ruilisi/fortune-sheet/pull/615

@Corbe30 this change might have caused it
