### ISSUE TITLE
SyntaxError: The requested module 'https://esm.sh/v135/lodash@4.17.21/es2022/lodash.development.mjs' doesn't provide an export named: 'isPlainObject'

### ISSUE THREAD

**Issue by Kreijstal** [ruilisi/fortune-sheet#626]
**Describe the bug**
You can't import fortune sheet from esm.sh

**To Reproduce**
try to import fortune sheet from esm.sh
`import("https://esm.sh/@fortune-sheet/react")`

for example
https://observablehq.com/d/37ef873372b7f3e4

**Expected behavior**
It doesn't error

**Additional context**
This is important if you want to try fortune-sheet from static websites, aka  serverless

**Comment by Kreijstal** [comment]
maybe
https://github.com/ruilisi/fortune-sheet/blob/5daf15bbdf29c97a0cbd454ba122caaa8ba84bb6/packages/core/src/modules/selection.ts#L1
should use 
_.isPlainObject  instead?

**Comment by Kreijstal** [comment]
> this is odd, i am unable to reproduce this as well. this code has been untouched for a long time now, but ideally both `_.isPlainObject` and `isPlainObject` should work. let me check this.

the javascript on https://observablehq.com/d/37ef873372b7f3e4 can be edited on real time, maybe you can see something?

**Comment by sanchit3008** [comment]
your pr _might_ solve this issue but i think this has something to do with the version exported by esm.sh. i havent seen any build errors locally due to this. i will merge your pr, but can you let me know if this is your first time using this library, and if you are able to use this library without a CDN?

**Comment by sanchit3008** [comment]
alright so the issue is that the cdn has the mjs file for lodash which does not support named exports. i will am merging your pr so that this can go live in the next release.

swapping lodash for lodash-es solves this issue, but it best to just use the default export everywhere.

**Comment by Kreijstal** [comment]
> your pr _might_ solve this issue but i think this has something to do with the version exported by esm.sh. i havent seen any build errors locally due to this. i will merge your pr, but can you let me know if this is your first time using this library, and if you are able to use this library without a CDN?

Managed to make it work but I had to overload react to get globalThis to work
```
 export default defineConfig({
   plugins: [react()],
   define: {
     global: 'globalThis',
   },
 })
 ```
 I think it will trigger the same error in the browser as browser has no `global` scope, only nodejs does

**Comment by sanchit3008** [comment]
It has been working fine for users until now in the browser though since
this is the first time this error has been reported. Though I have merged
your pr so that should take the uncertainty out.
