### ISSUE TITLE
怎么使用更多数字格式

### ISSUE THREAD

**Issue by Renkiee** [ruilisi/fortune-sheet#629]
怎么使用更多数字格式，感觉代码是有实现的

**Comment by sanchit3008** [comment]
which number formats do you require? we can look into it.

**Comment by Renkiee** [comment]
我想要自定义数字格式，例如加电流单位电压单位  ex: 1.00A 200.00V

**Comment by Corbe30** [comment]
Hi, will manually adding hard-coded support for V, A and Ω work for V1?
Later, we can add support for custom user-defined number formats in V2.
