### ISSUE TITLE
[Merge Cell] Merge cell config is not working as expected

### ISSUE THREAD

**Issue by nguyenpr9** [ruilisi/fortune-sheet#640]
**Describe the bug**
The merge cell feature in the FortuneSheet library does not work as expected. When a merge cell configuration is applied, the behavior deviates from the intended functionality.

**To Reproduce**
1. Set up a FortuneSheet instance with the following data configuration
```
const data = [
    {
        name: "Sheet1",
        celldata: [
            { r: 0, c: 0, v: { v: "Merged Cell" } },
            { r: 0, c: 1, v: {} },
            { r: 1, c: 0, v: {} },
            { r: 1, c: 1, v: {} },
        ],
        config: {
            merge: {
                "0_0": { r: 0, c: 0, rs: 2, cs: 2 }, // Merge (0,0) to (1,1)
            },
        },
    },
];

```
2. Observe the sheet's rendering and interaction with the merged cells.

**Actual behavior**
The cells from (0,0) to (1,1) was not visually merge into a single cell.

**Expected behavior**
The cells from (0,0) to (1,1) should visually merge into a single cell.

**Comment by sanchit3008** [comment]
```js
const data = {
  name: "Sheet1",
  celldata: [
    { r: 0, c: 0, v: { v: "Merged Cell", mc: { r: 0, c: 0, rs: 2, cs: 2 } } },
    { r: 0, c: 1, v: { mc: { r: 0, c: 0 } } },
    { r: 1, c: 0, v: { mc: { r: 0, c: 0 } } },
    { r: 1, c: 1, v: { mc: { r: 0, c: 0 } } },
  ],
  config: {
    merge: {
      "0_0": { r: 0, c: 0, rs: 2, cs: 2 }, // Merge (0,0) to (1,1)
    },
  },
};
```

use this

**Comment by nguyenpr9** [comment]
@sanchit3008  I must be config at Celldata array? So config.merge is no effect?

**Comment by sanchit3008** [comment]
you need to specify it in both the merge and the individual cells in cell data. the starting cell should have r,c,rs and cs. other merged cells which arent the starting pt of the merge just need r and c entries corresponding to the starting pt of the merged entity.

**Comment by nguyenpr9** [comment]
Thanks @sanchit3008 . But I have another issue when I combine merge and border, The border will not appear. Will you help me check this?

```
const data = {
  name: "Sheet1",
  celldata: [
    { r: 0, c: 0, v: { v: "Merged Cell", mc: { r: 0, c: 0, rs: 2, cs: 2 } } },
    { r: 0, c: 1, v: { mc: { r: 0, c: 0 } } },
    { r: 1, c: 0, v: { mc: { r: 0, c: 0 } } },
    { r: 1, c: 1, v: { mc: { r: 0, c: 0 } } },
  ],
  config: {
    merge: {
      "0_0": { r: 0, c: 0, rs: 2, cs: 2 }, // Merge (0,0) to (1,1)
    },
    borderInfo: [
      {
        rangeType: "range",
        borderType: "border-outside",
        style: "3",
        color: "#0000ff",
        range: [{
          row: [0, 1],
          column: [0, 1]
        }]
      }
    ],
  },
};

```

**Comment by sanchit3008** [comment]
what is the intended behaviour? do you need a border around 0,0 till 1,1?

**Comment by sanchit3008** [comment]
```
 borderInfo: [
      {
        rangeType: "range",
        borderType: "border-all",
        style: "3",
        color: "#0000ff",
        range: [
          {
            row: [0, 1],
            column: [0, 1],
          },
        ],
      },
    ],
```

i can see the border using this

<img width="270" alt="image" src="https://github.com/user-attachments/assets/6294cd7d-03e0-4d2d-997b-925d1658a461">

**Comment by nguyenpr9** [comment]
It seem like it only work on storybook. Will you help me check it again. I update the latest version of fortune-sheet but it still not working as expected

**Comment by sanchit3008** [comment]
please share your code, output and expected output
