### ISSUE TITLE
怎么主动执行sheet的失焦事件

### ISSUE THREAD

**Issue by Renkiee** [ruilisi/fortune-sheet#645]
输入内容后，直接点击外面的保存按钮获取不到cell value, 我应该怎么主动执行失焦事件

**Comment by sanchit3008** [comment]
are you pressing enter/return after typing in the cell ?

**Comment by Renkiee** [comment]
no enter, i input some value, and click extra save button, so i'm not get cell value。

**Comment by sanchit3008** [comment]
Can you try once after pressing enter upon input and then clicking save

**Comment by Renkiee** [comment]
是的，输入内容后按enter，然后点击保存按钮是可以获取到单元格内容的。但是我们有些用户习惯输入内容后不按enter直接点击保存，如果有一个主动模拟触发enter的事件就太棒了。

**Comment by sanchit3008** [comment]
There is no inbuilt method but I could hack together the following code to programmaticallly press enter - 

```js
const enterEvent = new KeyboardEvent("keydown", {
  key: "Enter",
  keyCode: 13, // Enter key code
  code: "Enter",
  which: 13,   // Legacy property for keyCode
  bubbles: true // Allows the event to bubble up
});

const inputElement = document.querySelector(".luckysheet-cell-selected-focus");

inputElement?.dispatchEvent(enterEvent);
```
