### ISSUE TITLE
Wrong words wrapping

### ISSUE THREAD

**Issue by SuyongSun** [ruilisi/fortune-sheet#67]
**Describe the bug**
Wrapping of words is clipped.

**To Reproduce**
Input some words especially chinese words, and set the cell wrapping, tune the length of words, will see the wrap cell clips one or two words.

**Expected behavior**
Correct wrapping calculation.

**Screenshots**
![image](https://user-images.githubusercontent.com/12286518/195793453-a994331e-af9b-4b76-8480-4990efe5baa6.png)

**Comment by Qaplagzy** [comment]
#73

**Comment by shuanhukexuejia** [comment]
> 

Thanks, will fix it soon

**Comment by shuanhukexuejia** [comment]
Has been fixed, see #83
