### ISSUE TITLE
Issue with line breaking

### ISSUE THREAD

**Issue by SuyongSun** [ruilisi/fortune-sheet#75]
**Describe the bug**
When there is multiple rows in a cell, then delete the last row, then the words aligment is wrong, especially under "horizontal center" style.

**To Reproduce**
1. Input multipe rows in the same cell with "alt+enter".
2. Delete the last row, and the count of ramining rows is more than one.
3. See the style error.

**Screenshots**
![image](https://user-images.githubusercontent.com/12286518/196836470-1fa27e37-4a84-4706-8351-103131a946bb.png)

**Comment by SuyongSun** [comment]
There is still a small error when the words has DBC case punctuation and SBC case punctuation at the same cell. This lead the last charater showing only half. If we look carefully at the cell, we found in the cell there is a bit larger blank in front of the cell's words.  
Screeshot as follow:  
![image](https://user-images.githubusercontent.com/12286518/196837551-c541a412-185c-4d2e-9996-066ea44bfad8.png)

**Comment by shuanhukexuejia** [comment]
Thanks for your report, I'm working on it now

**Comment by shuanhukexuejia** [comment]
Has been fixed, see #83

**Comment by SuyongSun** [comment]
Some issues complement:
1. Alignment is correct, but there is a extra blank row below the last row, so it can not be stay in center when style is vertical centralized. 
![lQLPJxbQLx-ohgQ7R7A9H5adCsi4bgNWJ7TNwEsA_71_59](https://user-images.githubusercontent.com/12286518/197922184-093e1e65-0548-4254-b72b-46c3c7b0e34d.png)

2. And when editing the cell, if needing to add new breaking row, input a "alt+enter" there will be two row generated. This support the above issue, though the original issue fixed, but extra blank row staying.
![lQLPJxbQLx-oh0RJRrBr0Rx8DIv2HQNWJ7TWAGEA_70_73](https://user-images.githubusercontent.com/12286518/197922530-02ff2eff-89ac-4f7e-9ef0-cb9cce167ece.png)

**Comment by shuanhukexuejia** [comment]
Sorry for that, its our negligence, see #87

**Comment by SuyongSun** [comment]
Take it easy. You have done a nice job.

**Comment by SuyongSun** [comment]
Sorry, one more thing.
The style has been fixed, but there is a minor falt with the RC cell value still have a extra "\r\n" in the end of value.
For example, we have a cell with value "test", we input "alt + enter" to add a new row then delete it, the value is expected still be "test", but the value is actually "test\r\n" in the data object. It will be impact other relation styles, such as export to excel, the cell is still with a extra blank row and the cell style is something wrong with this.
![image](https://user-images.githubusercontent.com/12286518/197953065-ec158f7f-e16f-499f-8b4f-3656d3c43603.png)
![image](https://user-images.githubusercontent.com/12286518/197953623-400dc869-7450-4087-bd42-e9a3bbc5486e.png)

**Comment by shuanhukexuejia** [comment]
You are right, have updated it.

**Comment by SuyongSun** [comment]
> You are right, have updated it.

Thanks, got the fixed.
