### ISSUE TITLE
安装包，然后有一个文件找不到

### ISSUE THREAD

**Issue by 1144075799** [ruilisi/fortune-sheet#8]
报错信息如下图所示:
![image](https://user-images.githubusercontent.com/38463468/164962483-18a468b4-c9de-470d-9bf3-35fb49b0baed.png)

**Comment by zyc9012** [comment]
你的编译工具配置(如webpack)要加入识别mjs和cjs文件后缀。之后我们会把文件后缀统一改成js

**Comment by 1144075799** [comment]
好的，修改好之后，麻烦回复一下，谢谢

**Comment by zyc9012** [comment]
@1144075799 已经好了。@fortune-sheet/formula-parser更新到了0.2.3

**Comment by 1144075799** [comment]
![image](https://user-images.githubusercontent.com/38463468/165060175-69fe2e90-5782-4297-8c52-d0aafc90ed35.png)

**Comment by 1144075799** [comment]
你好，我现在项目里面只有"@fortune-sheet/react": "^0.3.0"这个包。而且我安装@fortune-sheet/formula-parser@0.2.3的时候，报出找不到这个包

**Comment by zyc9012** [comment]
@1144075799 修复了
