### ISSUE TITLE
怎么跑线上的协同demo

### ISSUE THREAD

**Issue by 1144075799** [ruilisi/fortune-sheet#9]
我打算执行协同的前端，在命令行执行 yarn storybook。报下面的报错
![image](https://user-images.githubusercontent.com/38463468/165069476-7a5e09e1-7cec-4c61-92a3-91052946bfb0.png)

请问怎么运行协同前端的代码

**Comment by zyc9012** [comment]
先进到 packages/formula-parser里 `yarn build`一下

**Comment by 1144075799** [comment]
早上好，我到 packages/formula-parser里执行 yarn build。然后我到项目根目录下面执行 yarn dev。
页面是打开了，但是我报了一个错误：
![image](https://user-images.githubusercontent.com/38463468/165199345-d83c577f-bda1-4d34-8a77-2b450613d897.png)

**Comment by zyc9012** [comment]
访问一下 http://localhost:8081/init （初始化数据），再刷新这个页面
