### ISSUE TITLE
单元格包含 <> 类似HTML标签时候.存在问题

### ISSUE THREAD

**Issue by HengCC** [ruilisi/fortune-sheet#93]
单元格包含 <> 类似HTML标签时候.存在问题
同时如果存在换行. 那么在复制该单元格进行粘贴的时候会有问题. 再次编辑原单元格,它的值可能也会出现丢失的情况

**Comment by jikoczl** [comment]
能否给出复现过程或者截图

**Comment by HengCC** [comment]
https://user-images.githubusercontent.com/6167532/199377536-3755bcbf-5eea-43d8-8935-7de0077f76c6.mov

FYI
